::: {.content-hidden}
Copyright (C) 2024-2025 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Appendix: 5T-OTA Small-Signal Output Impedance {#sec-5t-ota-zout}

This section gives additional details to the analysis presented in @sec-basic-ota-small-signal.
Here we provide the full calculation of the output impedance/conductance of the 5T-OTA for frequencies below the dominant pole, i.e. we neglect any capacitors. 

{{< include /content/appendix/_fig_basic_ota_small_signal_zout.qmd >}}

## Open-Loop Configuration
For the open-loop case, the gates of $M_1$ and $M_2$ are tied to ground and thus, both $\Vgs$ are equal.
$$
V_\mathrm{in,p} = V_\mathrm{in,n} = 0\,\text{V}
$$
$$
\Vgs[1] = \Vgs[2]
$$ {#eq-app-vbufzout-vin-ol}

KCL at the output node:
$$
I_\mathrm{out} - \gds[4] V_\mathrm{out} - \gm[34]\Vgs[34] - I_{\gds[2]} - \gm[2] \Vgs[2] = 0
$$ {#eq-app-vbufzout-kcl-vout-ol}

KCL at the tail node:
$$
\gm[1] \Vgs[1] + \gm[2] \Vgs[2] + I_{\gds[2]} + \gds[5] \Vgs[2] = 0
$$

Using @eq-app-vbufzout-vin-ol we can eliminate $\Vgs[1]$ and solve for $I_{\gds[2]}$.
$$
I_{\gds[2]} = -\left( \gm[1] + \gm[2] + \gds[5] \right) \Vgs[2]
$$ {#eq-app-vbufzout-igds2}

Furthermore, we need an expression for $\Vgs[34]$. Ohm's law at the conductance $\gm[34]$ will suffice.
$$
\Vgs[34] = -\frac{\gm[1]}{\gm[34]} \Vgs[1]
$$ {#eq-app-vbufzout-vgs34-ol}

KVL from the output node down to ground (over $\gds[2]$ and $\gds[5]$) in combination with @eq-app-vbufzout-igds2 gives us an expression for $\Vgs[2]$
$$
\Vgs[2] = -\frac{\gds[2]}{\gm[1] + \gm[2] + \gds[2] + \gds[5]} V_\mathrm{out}
$$ {#eq-app-vbufzout-vgs2-ol}

Now, we can plug in all quantities into @eq-app-vbufzout-kcl-vout-ol. First, @eq-app-vbufzout-igds2 is inserted, which provides an expression for the current through the output conductance $\gds[2]$ of $M_2$. 
$$
I_\mathrm{out} - \gds[4] V_\mathrm{out} - \gm[34] \Vgs[34] + \left( \gm[1] + \gds[5] \right) \Vgs[2] = 0
$$

Second, $\Vgs[34]$ is substituted by @eq-app-vbufzout-vgs34-ol. Since we have assumed a matched pair of transistors for the current mirror comprised of $M_3$ and $M_4$, $\gm[34]$ perfectly cancels out of the equation, and is effectively replaced by the transconductance $\gm[1]$ of the input transistor $M_1$.
$$
I_\mathrm{out} - \gds[4] V_\mathrm{out} + \left( 2\gm[1] + \gds[5] \right) \Vgs[2] = 0
$$

Third, @eq-app-vbufzout-vgs2-ol gives as an expression for the last remaining unknown $\Vgs[2]$. Thus, the factor in front of $V_\mathrm{out}$ defines the conductance at the output node.
$$
I_\mathrm{out} - \left[ \gds[4] + \left( 2\gm[1] + \gds[5] \right) \frac{\gds[2]}{\gm[1] + \gm[2] + \gds[2] + \gds[5]} \right] V_\mathrm{out} = 0
$$ {#eq-app-vbufzout-zout-ol-1}
Before, we interpret this result, we use are assumption of matched input transistors ($\gm[12]=\gm[1]=\gm[2]$) and slightly rearrange the equation to give us more insight.
$$
I_\mathrm{out} - \left[ \gds[4] + \frac{\gds[2] \cdot \left( 2\gm[12] + \gds[5] \right)}{\gds[2] + \left( 2\gm[12] + \gds[5] \right)} \right] V_\mathrm{out} = 0
$$ {#eq-app-vbufzout-zout-ol-2}
Now, we can identify the common equation of the total resistance of two parallel resistors. However, we are dealing with conductances here, so the same equation describes the total conductance of two conductances in series, while parallel conductances are simply summed. In parallel to $\gds[4]$, there is effectively the series connection of $\gds[2]$ and $\left(2\gm[12]+\gds[5]\right)$ at work.
If we apply the general assumption of $\gm \gg \gds$, only the parallel connection of $\gds[4]$ and $\gds[2]$ remains. Therefore, moving $\gds[2] + \gds[4]$ in parallel to $C_\mathrm{load}$ in @sec-basic-ota-small-signal was valid.
$$
\frac{I_\mathrm{out}}{V_\mathrm{out}} \approx \gds[4] + \gds[2]
$$ {#eq-app-vbufzout-zout-ol-3}

## Closed-Loop Configuration
In contrast to the open-loop case, we keep the gate of $M_1$ connected to ground and tie the input of $M_2$ to the output node $V_\mathrm{out}$.
$$
V_\mathrm{in,n} = V_\mathrm{out}
$$ {#eq-app-vbufzout-vin-cl}

KCL at the output node:
$$
I_\mathrm{out} - \gds[4] V_\mathrm{out} - \gm[34] \Vgs[34] - \gds[2] \Vgs[2] - \gm[2] \Vgs[2] = 0
$$ {#eq-app-vbufzout-kcl-vout-cl}

We use KVL from the output node down to ground to find an expression for $\Vgs[2]$.
$$
\Vgs[2] =  V_\mathrm{out} + \Vgs[1]
$$ {#eq-app-vbufzout-kvl-vout-cl}

KCL at the tail node:
$$
\gm[1]\Vgs[1] + \gm[2]\Vgs[2] + \gds[2]\Vgs[2] + \gds[5]\Vgs[2] = 0
$$ {#eq-app-vbufzout-kcl-vtail-cl}


Using @eq-app-vbufzout-kvl-vout-cl to substitute $\Vgs[2]$ in {#eq-app-vbufzout-kcl-vtail-cl} we find an equation for $\Vgs[1]$.
$$
\Vgs[1] = -\frac{\gm[2] + \gds[2]}{\gm[1] + \gm[2] + \gds[2] + \gds[5]} V_\mathrm{out}
$$ {#eq-app-vbufzout-vgs1-cl}

Again, we derive the output conductance by plugging @eq-app-vbufzout-kvl-vout-cl, @eq-app-vbufzout-vgs34-ol and @eq-app-vbufzout-vgs1-cl step by step into @eq-app-vbufzout-kcl-vout-cl. First, we use @eq-app-vbufzout-kvl-vout-cl to eliminate $\Vgs[2]$.
$$
I_\mathrm{out} -\left( \gds[4] + \gds[2] + \gm[2] \right) V_\mathrm{out} - \gm[34] \Vgs[34] - \left( \gds[2] + \gm[2] \right) \Vgs[1] = 0
$$

Second, @eq-app-vbufzout-vgs34-ol also holds for the closed-loop case and lets us eliminate $\Vgs[34]$.
$$
I_\mathrm{out} -\left( \gds[4] + \gds[2] + \gm[2] \right) V_\mathrm{out} - \left( \gds[2] + \gm[2] - \gm[1] \right) \Vgs[1] = 0
$$

Third, we use @eq-app-vbufzout-vgs1-cl to eliminate the remaining unknown $\Vgs[1]$.
$$
I_\mathrm{out} -\left( \gds[4] + \gds[2] + \gm[2] \right) V_\mathrm{out} + \left( \gds[2] + \gm[2] - \gm[1] \right) \frac{\gm[2] + \gds[2]}{\gm[1] + \gm[2] + \gds[2] + \gds[5]} V_\mathrm{out} = 0
$$

A more simpler result can be obtained, if we neglect $\gds[2]$ and $\gds[5]$ in @eq-app-vbufzout-vgs1-cl first ($\gm \gg \gds$) and then plug it into our main equation. Additionally, we use $\gm[12]=\gm[1]=\gm[2]$ to further simplify the equation.
$$
I_\mathrm{out} -\left( \gds[4] + \frac{3}{2} \gds[2] + \gm[12] \right) V_\mathrm{out} \approx 0
$$

If we apply $\gm \gg \gds$ again, we arrive at the same result which was used for the noise calculation in @sec-basic-ota-small-signal, compare the expression for $Y'_\mathrm{load}$ given by @eq-basic-ota-output-noise-yload . 
$$
I_\mathrm{out} - \gm[12] V_\mathrm{out} \approx 0
$$
