<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Harald Pretl">
<meta name="author" content="Michael Koefinger">
<meta name="dcterms.date" content="2024-08-21">

<title>Analog Circuit Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Analog Circuit Design">
<meta name="citation_author" content="Harald Pretl">
<meta name="citation_author" content="Michael Koefinger">
<meta name="citation_publication_date" content="2024-08-21">
<meta name="citation_cover_date" content="2024-08-21">
<meta name="citation_year" content="2024">
<meta name="citation_online_date" content="2024-08-21">
<meta name="citation_language" content="en-US">
<meta name="citation_reference" content="citation_title=Measurement of loop gain in feedback systems;,citation_abstract=In this design of a feedback system it is desirable to make experimental measurements of the loop gain as a function of frequency to ensure that the physical system operates as analytically predicted or, if not, to supply information upon which a design correction can be based. In high loop-gain systems it is desirable that the loop-gain measurement be made without opening the loop. This paper discusses practical methods of measuring and interpreting the results for loop gain of the closed-loop system by a voltage injection or a current-injection technique ; extension to the case in which the measurement can be made even though the system is unstable ; and extension to the case in which neither the voltage nor current-injection technique alone is adequate, but in which a combination of both permits the true loop gain to be derived. These techniques have been found useful not only in linear feedback systems but also in describing-function analysis of switching-mode converters and regulators.;,citation_author=R. D. Middlebrook;,citation_publication_date=1975;,citation_cover_date=1975;,citation_year=1975;,citation_issue=4;,citation_doi=10.1080/00207217508920421;,citation_issn=0020-7217;,citation_volume=38;,citation_journal_title=International Journal of Electronics;">
<meta name="citation_reference" content="citation_title=Verifying the diode–capacitor circuit voltage decay;,citation_author=Edward H. Hellen;,citation_publication_date=2003-08;,citation_cover_date=2003-08;,citation_year=2003;,citation_issue=8;,citation_doi=10.1119/1.1578070;,citation_volume=71;,citation_journal_title=American Journal of Physics;">
<meta name="citation_reference" content="citation_title=SPICE2: A computer program to simulate semiconductor circuits;,citation_author=Laurence W. Nagel;,citation_publication_date=1975-05;,citation_cover_date=1975-05;,citation_year=1975;,citation_fulltext_html_url=http://www2.eecs.berkeley.edu/Pubs/TechRpts/1975/9602.html;,citation_dissertation_institution=EECS Department, University of California, Berkeley;">
<meta name="citation_reference" content="citation_title=Systematic design of analog CMOS circuits: Using pre-computed lookup tables;,citation_author=Paul G. A. Jespers;,citation_author=Boris Murmann;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;">
<meta name="citation_reference" content="citation_title=Modern semiconductor devices for integrated circuits;,citation_author=Chenming Hu;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;">
<meta name="citation_reference" content="citation_title=Operation and modeling of the MOS transistor;,citation_author=Yannis Tsividis;,citation_author=Colin McAndrew;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Analog Circuit Design</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Harald Pretl <a href="mailto:harald.pretl@jku.at" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        <a href="www.jku.at">
                        Johannes Kepler University
                        </a>
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Michael Koefinger <a href="mailto:michael.koefinger@jku.at" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        <a href="www.jku.at">
                        Johannes Kepler University
                        </a>
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
                <div>
            <div class="quarto-title-meta-heading">Published</div>
            <div class="quarto-title-meta-contents">
              <p class="date">August 21, 2024</p>
            </div>
          </div>
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.pdf"><i class="bi bi-file-pdf"></i>PDF</a></p></div></div></div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro">Introduction</a>
  <ul class="collapse">
  <li><a href="#ihps-sg13g2-130nm-cmos-technology" id="toc-ihps-sg13g2-130nm-cmos-technology" class="nav-link" data-scroll-target="#ihps-sg13g2-130nm-cmos-technology">IHP’s SG13G2 130nm CMOS Technology</a></li>
  <li><a href="#schematic-entry-using-xschem" id="toc-schematic-entry-using-xschem" class="nav-link" data-scroll-target="#schematic-entry-using-xschem">Schematic Entry Using Xschem</a></li>
  <li><a href="#circuit-simulation-using-ngspice" id="toc-circuit-simulation-using-ngspice" class="nav-link" data-scroll-target="#circuit-simulation-using-ngspice">Circuit Simulation Using ngspice</a></li>
  <li><a href="#integrated-ic-design-environment-iic-osic-tools" id="toc-integrated-ic-design-environment-iic-osic-tools" class="nav-link" data-scroll-target="#integrated-ic-design-environment-iic-osic-tools">Integrated IC Design Environment (IIC-OSIC-TOOLS)</a></li>
  </ul></li>
  <li><a href="#sec-first-steps" id="toc-sec-first-steps" class="nav-link" data-scroll-target="#sec-first-steps">First Steps</a>
  <ul class="collapse">
  <li><a href="#sec-mosfet" id="toc-sec-mosfet" class="nav-link" data-scroll-target="#sec-mosfet">The Metal-Oxide-Semiconductor Field-Effect-Transistor (MOSFET)</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#sec-gmid-method" id="toc-sec-gmid-method" class="nav-link" data-scroll-target="#sec-gmid-method">Transistor Sizing Using gm/ID Methodology</a>
  <ul class="collapse">
  <li><a href="#mosfet-characterization-testbench" id="toc-mosfet-characterization-testbench" class="nav-link" data-scroll-target="#mosfet-characterization-testbench">MOSFET Characterization Testbench</a></li>
  <li><a href="#sec-techsweep-nmos" id="toc-sec-techsweep-nmos" class="nav-link" data-scroll-target="#sec-techsweep-nmos">NMOS Characterization</a></li>
  <li><a href="#sec-techsweep-pmos" id="toc-sec-techsweep-pmos" class="nav-link" data-scroll-target="#sec-techsweep-pmos">PMOS Characterization</a></li>
  </ul></li>
  <li><a href="#sec-mosfet-diode" id="toc-sec-mosfet-diode" class="nav-link" data-scroll-target="#sec-mosfet-diode">First Circuit: MOSFET Diode</a>
  <ul class="collapse">
  <li><a href="#mosfet-diode-sizing" id="toc-mosfet-diode-sizing" class="nav-link" data-scroll-target="#mosfet-diode-sizing">MOSFET Diode Sizing</a></li>
  <li><a href="#mosfet-diode-large-signal-behaviour" id="toc-mosfet-diode-large-signal-behaviour" class="nav-link" data-scroll-target="#mosfet-diode-large-signal-behaviour">MOSFET Diode Large-Signal Behaviour</a></li>
  <li><a href="#mosfet-diode-small-signal-analysis" id="toc-mosfet-diode-small-signal-analysis" class="nav-link" data-scroll-target="#mosfet-diode-small-signal-analysis">MOSFET Diode Small-Signal Analysis</a></li>
  <li><a href="#mosfet-diode-stability-analysis" id="toc-mosfet-diode-stability-analysis" class="nav-link" data-scroll-target="#mosfet-diode-stability-analysis">MOSFET Diode Stability Analysis</a></li>
  <li><a href="#mosfet-diode-noise-calculation" id="toc-mosfet-diode-noise-calculation" class="nav-link" data-scroll-target="#mosfet-diode-noise-calculation">MOSFET Diode Noise Calculation</a></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1">Conclusion</a></li>
  </ul></li>
  <li><a href="#sec-current-mirror" id="toc-sec-current-mirror" class="nav-link" data-scroll-target="#sec-current-mirror">Current Mirror</a></li>
  <li><a href="#sec-diff-pair" id="toc-sec-diff-pair" class="nav-link" data-scroll-target="#sec-diff-pair">Differential Pair</a>
  <ul class="collapse">
  <li><a href="#differential-operation-of-the-diffpair" id="toc-differential-operation-of-the-diffpair" class="nav-link" data-scroll-target="#differential-operation-of-the-diffpair">Differential Operation of the Diffpair</a></li>
  <li><a href="#common-mode-operation-of-the-diffpair" id="toc-common-mode-operation-of-the-diffpair" class="nav-link" data-scroll-target="#common-mode-operation-of-the-diffpair">Common-Mode Operation of the Diffpair</a></li>
  </ul></li>
  <li><a href="#sec-basic-ota" id="toc-sec-basic-ota" class="nav-link" data-scroll-target="#sec-basic-ota">A Basic 5-Transistor OTA</a>
  <ul class="collapse">
  <li><a href="#voltage-buffer-with-ota" id="toc-voltage-buffer-with-ota" class="nav-link" data-scroll-target="#voltage-buffer-with-ota">Voltage Buffer with OTA</a></li>
  <li><a href="#large-signal-analysis-of-the-ota" id="toc-large-signal-analysis-of-the-ota" class="nav-link" data-scroll-target="#large-signal-analysis-of-the-ota">Large-Signal Analysis of the OTA</a></li>
  <li><a href="#small-signal-analysis-of-the-ota" id="toc-small-signal-analysis-of-the-ota" class="nav-link" data-scroll-target="#small-signal-analysis-of-the-ota">Small-Signal Analysis of the OTA</a></li>
  </ul></li>
  <li><a href="#cascode-stage" id="toc-cascode-stage" class="nav-link" data-scroll-target="#cascode-stage">Cascode Stage</a></li>
  <li><a href="#a-fully-differential-ota" id="toc-a-fully-differential-ota" class="nav-link" data-scroll-target="#a-fully-differential-ota">A Fully-Differential OTA</a></li>
  <li><a href="#biasing-the-ota" id="toc-biasing-the-ota" class="nav-link" data-scroll-target="#biasing-the-ota">Biasing the OTA</a></li>
  <li><a href="#an-rc-opamp-filter" id="toc-an-rc-opamp-filter" class="nav-link" data-scroll-target="#an-rc-opamp-filter">An RC-OPAMP Filter</a></li>
  <li><a href="#summary-conclusion" id="toc-summary-conclusion" class="nav-link" data-scroll-target="#summary-conclusion">Summary &amp; Conclusion</a></li>
  <li><a href="#appendix-ngspice-cheat-sheet" id="toc-appendix-ngspice-cheat-sheet" class="nav-link" data-scroll-target="#appendix-ngspice-cheat-sheet">Appendix: ngspice Cheat Sheet</a></li>
  <li><a href="#appendix-xschem-cheat-sheet" id="toc-appendix-xschem-cheat-sheet" class="nav-link" data-scroll-target="#appendix-xschem-cheat-sheet">Appendix: Xschem Cheat Sheet</a></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="sizing/techsweep_sg13_txt_to_mat-preview.html"><i class="bi bi-journal-code"></i>Conversion of TXT to MAT for gm/ID result files for SG13G2</a></li><li><a href="sizing/techsweep_sg13_plots_nmos-preview.html"><i class="bi bi-journal-code"></i>MOSFET gm/ID Evaluation Script for IHP SG13G2</a></li><li><a href="sizing/techsweep_sg13_plots_pmos-preview.html"><i class="bi bi-journal-code"></i>MOSFET gm/ID Evaluation Script for IHP SG13G2</a></li><li><a href="sizing/lookup_sg13-preview.html"><i class="bi bi-journal-code"></i>MOSFET gm/ID Lookup for IHP SG13G2</a></li><li><a href="sizing/sizing_current_mirror-preview.html"><i class="bi bi-journal-code"></i>Sizing for Improved Current Mirror</a></li><li><a href="sizing/sizing_mosfet_diode-preview.html"><i class="bi bi-journal-code"></i>Sizing for MOSFET Diode Example</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<section id="sec-intro" class="level2">
<h2 class="anchored" data-anchor-id="sec-intro">Introduction</h2>
<p>This is the material for an intermediate-level MOSFET circuit design course, held at JKU under course number 336.009 (“KV Analoge Schaltungstechnik”).</p>
<p>The course makes heavy use of circuit simulation, using <strong>Xschem</strong> for schematic entry and <strong>ngspice</strong> for simulation. The 130nm CMOS technology <strong>SG13G2</strong> from IHP Microelectronics is used.</p>
<p>Tools and PDK are integrated in the <strong>IIC-OSIC-TOOLS</strong> Docker image, which will be used during the coursework.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>All course material is made publicly available on GitHub and shared under the Apache-2.0 license.</p>
</div>
</div>
<section id="ihps-sg13g2-130nm-cmos-technology" class="level3">
<h3 class="anchored" data-anchor-id="ihps-sg13g2-130nm-cmos-technology">IHP’s SG13G2 130nm CMOS Technology</h3>
<p>SG13G2 is the name of a 130nm CMOS technology (strictly speaking BiCMOS) from IHP Microelectronics. It features low-voltage (thin-oxide) core MOSFET, high-voltage (thick-oxide) I/O MOSFET, various types of linear resistors, and 7 layers of Aluminium metallization (5 thin plus 2 thick metal layers). This PDK is open-source, and the complete process specification can be found at <a href="https://github.com/IHP-GmbH/IHP-Open-PDK/blob/main/ihp-sg13g2/libs.doc/doc/SG13G2_os_process_spec.pdf">SG13G2 process specification</a>. While we will not do layouts in this course, the layout rules can be found at <a href="https://github.com/IHP-GmbH/IHP-Open-PDK/blob/main/ihp-sg13g2/libs.doc/doc/SG13G2_os_layout_rules.pdf">SG13G2 layout rules</a>.</p>
<p>For our circuit design, the most important parameters of the available devices are summarized in the following:</p>
<ul>
<li><strong>Low-voltage NMOS</strong>: Device <code>sg13_lv_nmos</code>; operating voltage nominal <span class="math inline">\(V_\mathrm{DD}=1.5\,\text{V}\)</span>, <span class="math inline">\(L_\mathrm{min}=0.13\,\mu\text{m}\)</span>, <span class="math inline">\(V_\mathrm{th}\approx 0.5\,\text{V}\)</span>; a triple-well option for the NMOS is available.</li>
<li><strong>Low-voltage PMOS</strong>: Device <code>sg13_lv_pmos</code>; operating voltage nominal <span class="math inline">\(V_\mathrm{DD}=1.5\,\text{V}\)</span>, <span class="math inline">\(L_\mathrm{min}=0.13\,\mu\text{m}\)</span>, <span class="math inline">\(V_\mathrm{th}\approx -0.47\,\text{V}\)</span>.</li>
<li><strong>High-voltage NMOS</strong>: Device <code>sg13_hv_nmos</code>; operating voltage nominal <span class="math inline">\(V_\mathrm{DD}=3.3\,\text{V}\)</span>, <span class="math inline">\(L_\mathrm{min}=0.45\,\mu\text{m}\)</span>, <span class="math inline">\(V_\mathrm{th}\approx 0.7\,\text{V}\)</span>; a triple-well option for the NMOS is available.</li>
<li><strong>High-voltage PMOS</strong>: Device <code>sg13_hv_pmos</code>; operating voltage nominal <span class="math inline">\(V_\mathrm{DD}=3.3\,\text{V}\)</span>, <span class="math inline">\(L_\mathrm{min}=0.45\,\mu\text{m}\)</span>, <span class="math inline">\(V_\mathrm{th}\approx -0.65\,\text{V}\)</span>.</li>
<li><strong>Silicided poly resistor</strong>: Device <code>rsil</code>; <span class="math inline">\(R_\square=7\,\Omega \pm 10\%\)</span>, <span class="math inline">\(\text{TC}_1=3100\,\text{ppm/K}\)</span></li>
<li><strong>Poly resistor</strong>: Device <code>rppd</code>; <span class="math inline">\(R_\square=260\,\Omega \pm 10\%\)</span>, <span class="math inline">\(\text{TC}_1=170\,\text{ppm/K}\)</span></li>
<li><strong>Poly resistor high</strong>: Device <code>rhigh</code>; <span class="math inline">\(R_\square=1360\,\Omega \pm 15\%\)</span>, <span class="math inline">\(\text{TC}_1=-2300\,\text{ppm/K}\)</span></li>
<li><strong>MIM capacitor</strong>: Device <code>cap_cmim</code>; <span class="math inline">\(C'=1.5\,\text{fF}/\mu\text{m}^2 \pm 10\%\)</span>, <span class="math inline">\(\text{VC}_1=-26\text{ppm/V}\)</span>, <span class="math inline">\(\text{TC}_1=3.6\text{ppm/K}\)</span>, breakdown voltage <span class="math inline">\(&gt;15\,\text{V}\)</span></li>
<li><strong>MOM capacitor</strong>: The metal stack is well-suited for MOM capacitors due to 5 thin metal layers, but no primitive capacitor device is available at this point.</li>
</ul>
</section>
<section id="schematic-entry-using-xschem" class="level3">
<h3 class="anchored" data-anchor-id="schematic-entry-using-xschem">Schematic Entry Using Xschem</h3>
<p>Xschem is an open-source schematic entry tool with emphasis on integrated circuits. For up-to-date information of the many features of Xschem and the basic operation of it please look at the available <a href="https://xschem.sourceforge.io/stefan/xschem_man/xschem_man.html">online documentation</a>. Usage of Xschem will be learned with the first few basic examples, essentially using a single MOSFET. The usage model of Xschem is that the schematic is hierarchically drawn, and the simulation and evaluation statements are contained in the schematics. Further, Xschem offers embedded graphing, which we will mostly use.</p>
</section>
<section id="circuit-simulation-using-ngspice" class="level3">
<h3 class="anchored" data-anchor-id="circuit-simulation-using-ngspice">Circuit Simulation Using ngspice</h3>
<p>ngspice is an open-source circuit simulator with SPICE dependency <span class="citation" data-cites="Nagel_1975">(<a href="#ref-Nagel_1975" role="doc-biblioref">Nagel 1975</a>)</span>. Besides the usual simulated types like <code>op</code> (operating point), <code>dc</code> (dc sweeps), <code>tran</code> (time-domain), or <code>ac</code> (small-signal frquency sweeps), ngspice offers a script-like control interface, where many different simulation controls and result evaluations can be done. For detailed information please refer to the latest <a href="https://ngspice.sourceforge.io/docs/ngspice-43-manual.pdf">online manual</a>.</p>
</section>
<section id="integrated-ic-design-environment-iic-osic-tools" class="level3">
<h3 class="anchored" data-anchor-id="integrated-ic-design-environment-iic-osic-tools">Integrated IC Design Environment (IIC-OSIC-TOOLS)</h3>
<p>In order to make use of the various required components (tools like Xschem and ngspice, PDKs like SG13G2) easier, we will use the <strong>IIC-OSIC-TOOLS</strong>. This is a pre-compiled Docker image which allows to do circuit design on a virtual machine on virtually any type of computing equipment (personal PC, Raspberry Pi, cloud server) on various operating systems (Windows, macOS, Linux). For further information like installed tools, how to setup a VM, etc. please look at <a href="https://github.com/iic-jku/IIC-OSIC-TOOLS">IIC-OSIC-TOOLS GitHub page</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please make sure to receive information about your personal VM access ahead of the course start.</p>
</div>
</div>
<p>Experienced users can install this image on their personal computer, for JKU students the IIC will host a VM on our compute cluster and provide personal login credentials.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this course, we assume that students have a basic knowledge of Linux and how to operate it using the terminal. If you are not yet familiar with Linux (which is basically a must when doing integrated circuit design as many tools are only available on Linux), then please check out a Linux introductory course or tutorial online, there are many ressources available.</p>
</div>
</div>
</section>
</section>
<section id="sec-first-steps" class="level2">
<h2 class="anchored" data-anchor-id="sec-first-steps">First Steps</h2>
<p>In this first chapter we will learn to use Xschem for schematic entry, and how to operate the ngspice SPICE simulator for circuit simulations. Further, we will make ourself familiar with the transistor and other passive components available in the IHP Microelectronics SG13G2 technology. While this is strictly speaking a BiCMOS technology offering MOSFETs as well as SiGe HBTs, we will use it as a pure CMOS technology.</p>
<section id="sec-mosfet" class="level3">
<h3 class="anchored" data-anchor-id="sec-mosfet">The Metal-Oxide-Semiconductor Field-Effect-Transistor (MOSFET)</h3>
<p>In this course, we will not dive into semiconductor physics and derive the device operation bottom-up starting from a fundamental level governed by quantum mechanics. Instead, we will treat the MOSFET as a macroscopic by assuming we have a 4-terminal device, and the performance of this device regarding its terminal voltages and currents we will largely derive from the simulation model.</p>
<p>The circuit symbol that we will use for the n-channel MOSFET is shown in <a href="#fig-nmos-symbol" class="quarto-xref">Figure&nbsp;1</a>, and for the p-channel MOSFET it is shown in <a href="#fig-pmos-symbol" class="quarto-xref">Figure&nbsp;2</a>. A control voltage between gate (“G”) and source (“S”) causes a current to flow between drain (“D”) and source. The MOSFET is a 4-terminal device, so the bulk (“B”) can also control the drain-source current flow. Often, the bulk is connected to source, and then the bulk terminal is not shown to declutter the schematics.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Strictly speaking is the drain-source current of a MOSFET controlled by the voltage between gate and bulk and the voltage between drain and source. Since bulk is often connected to source anyway, and many circuit designers historically were already familiar with the operation of the bipolar junction transistor, it is common to consider the gate-source voltage (besides the drain-source voltage) as the controlling voltage.</p>
<p>This focus on gate-source implies that the source is special compared to the drain. In a typical physical MOSFET, however, the drain and source are constructed exactly the same, and which terminal is drain, and which terminal is source, is only determined by the applied voltage potentials, and can change dynamically during operation (think of a MOSFET operating as a switch… which side is the drain, which side is the source?).</p>
<p>Unfortunately, this focus on a “special” source has made its way into some MOSFET compact models. The model that is used in SG13G2 luckily uses the PSP model, which is formulated symmetrically with regards to drain and source, and is thus very well suited for analog and RF circuit design. For a detailed understanding of the PSP model please refer to the <a href="https://www.nxp.com/wcm_documents/models/mos-models/model-psp/psp102p4_summary.pdf">model documentation</a>.</p>
</div>
</div>
<div id="cell-fig-nmos-symbol" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-nmos-symbol" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nmos-symbol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-nmos-symbol-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Circuit symbol of n-channel MOSFET."><img src="index_files/figure-html/fig-nmos-symbol-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nmos-symbol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Circuit symbol of n-channel MOSFET.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-pmos-symbol" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-pmos-symbol" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pmos-symbol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-pmos-symbol-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Circuit symbol of p-channel MOSFET."><img src="index_files/figure-html/fig-pmos-symbol-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pmos-symbol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Circuit symbol of p-channel MOSFET.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For hand calculations and theoretical discussions we will use the following simplified large-signal model, shown in <a href="#fig-mosfet-large-signal-model" class="quarto-xref">Figure&nbsp;3</a>. A current source <span class="math inline">\(I_\mathrm{DS}\)</span> models the current flow between drain and source, and it is controlled by the three control voltages <span class="math inline">\(V_\mathrm{GS}\)</span>, <span class="math inline">\(V_\mathrm{DS}\)</span>, and <span class="math inline">\(V_\mathrm{SB}\)</span>. Note that in this way (since <span class="math inline">\(I_\mathrm{DS}= f(V_\mathrm{DS})\)</span>) also a resistive behavior between D and S can be modelled. In case that B and S are shorted then simply <span class="math inline">\(V_\mathrm{SB} = 0\)</span>.</p>
<div id="cell-fig-mosfet-large-signal-model" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-mosfet-large-signal-model" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-large-signal-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-mosfet-large-signal-model-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: The MOSFET large-signal model."><img src="index_files/figure-html/fig-mosfet-large-signal-model-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-large-signal-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The MOSFET large-signal model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In an ideal MOSFET no dc current is flowing into the gate, the behavior is purely capacitive. We model this by two capacitors: <span class="math inline">\(C_\mathrm{GG}= C_\mathrm{GS}+ C_\mathrm{GD}\)</span> is the total capacitance when looking into the gate of the MOSFET. <span class="math inline">\(C_\mathrm{GS}\)</span> is usually the dominant capacitance, and <span class="math inline">\(C_\mathrm{GD}\)</span> models the capacitive feedback between D and G, usually induced by a topological overlap capacitance in the physical construction of the MOSFET. This capacitance is often small compared to <span class="math inline">\(C_\mathrm{GS}\)</span>, but in situations where we have a large voltage swing at the drain this capacitance will be affected by the <a href="https://en.wikipedia.org/wiki/Miller_effect">Miller effect</a>. In hand calculations we will often set <span class="math inline">\(C_\mathrm{GD}= 0\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The bulk connection in <a href="#fig-mosfet-large-signal-model" class="quarto-xref">Figure&nbsp;3</a> seems floating as we only consider it a control terminal, where the potential difference between source and bulk influences the behaviour of the MOSFET. However, we do not consider resistive or capacitive effects associated with this node, which is of course a gross simplification, but nevertheless one we will make in this course.</p>
</div>
</div>
<p>Now, as we are skipping the bottom-up approach of deriving the MOSFET large-signal behaviour from basic principles, we need to understand the behaviour of the elements of the large-signal model in <a href="#fig-mosfet-large-signal-model" class="quarto-xref">Figure&nbsp;3</a> by using a circuit simulator and observing what happens. And generally, a first step in any new IC technology should be to investigate basic MOSFET performance, by doing simple dc sweeps of <span class="math inline">\(V_\mathrm{GS}\)</span> and <span class="math inline">\(V_\mathrm{DS}\)</span> and looking at <span class="math inline">\(I_\mathrm{DS}\)</span> and other large- and small-signal parameters.</p>
<p>As a side note, the students who want to understand MOSFET behaviour from a physical angle should consult the MOSFET chapter from the JKU course “Design of Complex Integrated Circuits” (VL 336.048). A great introduction into MOSFET operation and fabrication is given in <span class="citation" data-cites="Chenming_Hu_2010">(<a href="#ref-Chenming_Hu_2010" role="doc-biblioref">Hu 2010</a>)</span>, which is available freely <a href="https://www.chu.berkeley.edu/modern-semiconductor-devices-for-integrated-circuits-chenming-calvin-hu-2010/">online</a> and is a recommended read. A very detailed description of the MOSFET (leaving usually no question unanswered) is provided in <span class="citation" data-cites="Tsividis_McAndrew_2011">(<a href="#ref-Tsividis_McAndrew_2011" role="doc-biblioref">Tsividis and McAndrew 2011</a>)</span>.</p>
<p>Now, in order to get started, basic Xschem testbenches are prepared, and first simple dc sweeps of various voltages and currents will be done. But before that, please look at the import note below!</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Throughout this material, we will stick to the following notations:</p>
<ul>
<li>A <strong>dc quantity</strong> is shown with an upper-case letter with upper-case subscripts, like <span class="math inline">\(V_\mathrm{GS}\)</span>.</li>
<li>Double-subscripts denote <strong>dc sources</strong>, like <span class="math inline">\(V_\mathrm{DD}\)</span> and <span class="math inline">\(V_\mathrm{SS}\)</span>.</li>
<li>An <strong>ac (small-signal) quantity</strong> is a lower-case letter with a lower-case subscript, like <span class="math inline">\(g_\mathrm{m}\)</span>.</li>
<li>A <strong>total quantity</strong> (dc plus ac) is shown as a lowercase letter with upper-case subscript, like <span class="math inline">\(i_\mathrm{DS}\)</span>.</li>
<li>A upper-case letter with a lower-case subscript is used to denote <strong>RMS quantities</strong>, like <span class="math inline">\(I_\mathrm{ds}\)</span>.</li>
</ul>
</div>
</div>
<section id="large-signal-mosfet-model" class="level4">
<h4 class="anchored" data-anchor-id="large-signal-mosfet-model">Large-Signal MOSFET Model</h4>
<p>We start with an investigation into the large-signal MOSFET model shown in <a href="#fig-mosfet-large-signal-model" class="quarto-xref">Figure&nbsp;3</a> by using the simple testbench for the LV NMOS shown in <a href="#fig-simple-nmos-tb" class="quarto-xref">Figure&nbsp;4</a>.</p>
<div id="fig-simple-nmos-tb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simple-nmos-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./xschem/dc_lv_nmos.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: Testbench for NMOS dc sweeps."><img src="./xschem/dc_lv_nmos.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simple-nmos-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Testbench for NMOS dc sweeps.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please try to execute the following steps and answer these questions:</p>
<ol type="1">
<li>Get the LV NMOS testbench (available at <a href="https://github.com/iic-jku/analog-circuit-design/blob/main/xschem/dc_lv_nmos.sch" class="uri">https://github.com/iic-jku/analog-circuit-design/blob/main/xschem/dc_lv_nmos.sch</a>) working in your IIC-OSIC-TOOLS environment.</li>
<li>Make yourself familiar with Xschem (change the schematic in various ways, run a simulation, graph the result).</li>
<li>Make youself familiar with ngspice (run various simulations, save nets and parameters, use the embedded Xschem graphing, explore the interactive ngspice shell to look at MOSFET model parameters).</li>
<li>Explore the LV NMOS <code>sg13_lv_nmos</code>:
<ol type="1">
<li>How is <span class="math inline">\(I_\mathrm{DS}\)</span> affected by <span class="math inline">\(V_\mathrm{GS}\)</span> and <span class="math inline">\(V_\mathrm{DS}\)</span>?</li>
<li>Change <span class="math inline">\(W\)</span> and <span class="math inline">\(L\)</span> of the MOSFET. What is the impact on the above parameters? Can you explain the variations?</li>
<li>When looking at the model parameters in ngspice, you see that there is a <span class="math inline">\(C_\mathrm{GD}\)</span> and a <span class="math inline">\(C_\mathrm{DG}\)</span>. Why is this, what could be the difference? Sometimes these capacitors show a negative value, why?</li>
</ol></li>
<li>Build testbenches in Xschem for the LV PMOS, the HV NMOS, and the HV PMOS. Explore the different results.
<ol type="1">
<li>For a given <span class="math inline">\(W\)</span> and <span class="math inline">\(L\)</span>, which device provides more drain current? How are the capacitances related?</li>
<li>If you would have to size an inverter, what would be the ideal ratio of <span class="math inline">\(W_p/W_n\)</span>? Will you exactly design this ratio, or are the reasons to deviate?</li>
<li>There are LV and HV MOSFETs, and you investigated the difference in performance. What is the rationale when designing circuits for selection either an LV type, and when to choose an HV type?</li>
</ol></li>
<li>Build a test bench to explore the body effect, start with LV NMOS.
<ol type="1">
<li>What happens when <span class="math inline">\(V_\mathrm{BS} \neq 0\)</span>?</li>
</ol></li>
</ol>
</div>
</div>
</section>
<section id="sec-mosfet-smallsignal-model" class="level4">
<h4 class="anchored" data-anchor-id="sec-mosfet-smallsignal-model">Small-Signal MOSFET Model</h4>
<p>As you have seen in the previous investigations, the large-signal model of <a href="#fig-mosfet-large-signal-model" class="quarto-xref">Figure&nbsp;3</a> describes the behaviour of the MOSFET across a wide range of voltages applied at the MOSFET terminals. Unfortunately, for hand analysis dealing with a nonlinear model is close to impossible, at the very least it is quite tedious.</p>
<p>However, for many practical situations, we bias a MOSFET with a set of dc voltages applied to its terminal, and only apply small signal excursions during operation. If we do this, we can linearize the large-signal model in this dc operating point, and resort to a small-signal model which can be very useful for hand calculations. Many experienced designers analyze their circuits by doing these kind of hand calculations and describing the circuit analytically, which is a great way to understand fundamental performance limits and relationships between parameters.</p>
<p>We will use the small-signal MOSFET model shown in <a href="#fig-mosfet-small-signal-model" class="quarto-xref">Figure&nbsp;5</a> for this course. The current-source <span class="math inline">\(i_\mathrm{ds}= g_\mathrm{m}v_\mathrm{gs}\)</span> models the drain current as a function of <span class="math inline">\(v_\mathrm{gs}\)</span>, and the resistor <span class="math inline">\(g_\mathrm{ds}\)</span> models the dependency of the drain current by <span class="math inline">\(v_\mathrm{ds}\)</span>. The drain current dependency on the source-bulk voltage (the so-called “body effect”) is introduced by the current source <span class="math inline">\(i_\mathrm{ds}= g_\mathrm{mb} v_\mathrm{sb}\)</span>.</p>
<div id="cell-fig-mosfet-small-signal-model" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-mosfet-small-signal-model" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-small-signal-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-mosfet-small-signal-model-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;5: The MOSFET small-signal model."><img src="index_files/figure-html/fig-mosfet-small-signal-model-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-small-signal-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: The MOSFET small-signal model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As any electronic device the MOSFET introduces noise into the circuit. In this course we will only consider the drain-source current noise of the MOSFET, given by <span class="math inline">\(\overline{I_\mathrm{n}^2} = 4 k T \gamma g_\mathrm{d0}\)</span> (<span class="math inline">\(\overline{I_\mathrm{n}^2}\)</span> is the power-spectral density of the noise in A<span class="math inline">\(^2\)</span>/Hz; <span class="math inline">\(k\)</span> is the Boltzmann constant; <span class="math inline">\(T\)</span> is the absolute temperature; <span class="math inline">\(\gamma\)</span> is a parameter in simplified theory changing between <span class="math inline">\(\gamma = 2/3\)</span> in saturation and <span class="math inline">\(\gamma =1\)</span> for triode operation; <span class="math inline">\(g_\mathrm{d0}\)</span> is equal to <span class="math inline">\(g_\mathrm{m}\)</span> in saturation and <span class="math inline">\(g_\mathrm{ds}\)</span> in triode).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sometimes we will refer to different operating modes of the MOSFET like “saturation” or “triode”. Generally speaking, when the drain-source voltage is small, then the MOSFET acts as a resistor, and this mode of operation we call “triode” mode. When the drain-source voltage is increased, at some point the drain-source current saturates and is no longer a strong function of the drain-source voltage. This mode is called “saturation” mode. As you can see in the large-signal investigations, these transitions happen gradually, and it is difficult to define a precise point where one operating mode switches to the other one. In this sense we use terms like “triode” and “saturation” only in an approximative sense.</p>
</div>
</div>
<p>Now we need to see how the small-signal parameters seen in <a href="#fig-mosfet-small-signal-model" class="quarto-xref">Figure&nbsp;5</a> can be investigated and estimated using circuit simulation.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please try to execute the following steps and answer the following questions:</p>
<ol type="1">
<li>Reuse the LV NMOS testbench (available at <a href="https://github.com/iic-jku/analog-circuit-design/blob/main/xschem/dc_lv_nmos.sch" class="uri">https://github.com/iic-jku/analog-circuit-design/blob/main/xschem/dc_lv_nmos.sch</a>).</li>
<li>Explore the LV NMOS <code>sg13_lv_nmos</code>:
<ol type="1">
<li>How are <span class="math inline">\(g_\mathrm{m}\)</span> and <span class="math inline">\(g_\mathrm{ds}\)</span> changing when you change the dc node voltages?</li>
<li>What is the ratio of <span class="math inline">\(g_\mathrm{m}\)</span> to <span class="math inline">\(g_\mathrm{mb}\)</span>? What is the physical reason behind this ratio (you might want to revisit MOSFET device physics at this point)?</li>
<li>Take a look at the device capacitances <span class="math inline">\(C_\mathrm{gs}\)</span> and <span class="math inline">\(C_\mathrm{gd}\)</span>. Why are they important? What is the relation to <span class="math inline">\(f_\mathrm{T}\)</span>? <em>Note: <span class="math inline">\(f_\mathrm{T}\)</span> is the transit frequency where the current gain of the MOSFET drops to 1, and can be approximated by <span class="math inline">\(2 \pi f_\mathrm{T} = g_\mathrm{m}/ C_\mathrm{gg}\)</span>.</em></li>
<li>Look at the drain noise current according to the MOSFET model and compare with a hand calculation of the noise. In the noise equation there is the factor <span class="math inline">\(\gamma\)</span>, which in triode is <span class="math inline">\(\gamma=1\)</span> and in saturation is <span class="math inline">\(\gamma=2/3\)</span> according to basic text books. Which value of <span class="math inline">\(\gamma\)</span> are you calculating? Why might it be different?</li>
</ol></li>
<li>Go back to your testbench for the LVS PMOS <code>sg13_lv_pmos</code>:
<ol type="1">
<li>What is the difference in <span class="math inline">\(g_\mathrm{m}\)</span>, <span class="math inline">\(g_\mathrm{ds}\)</span>, and other parameters between the NMOS and the PMOS? Why could they be different?</li>
</ol></li>
</ol>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Congratulations for making it thus far! By now you should have a solid grasp of the tool handling of Xschem and ngspice, and you should be familiar with the large- and small-signal operation of both NMOS and PMOS, and the parameters describing these behaviours. If you feel you are not sufficiently fluent in these things, please go back to the beginning of <a href="#sec-mosfet" class="quarto-xref">Section&nbsp;2.1</a> and revisit the relevant sections, or dive into further reading about the MOSFET operation, like in <span class="citation" data-cites="Chenming_Hu_2010">(<a href="#ref-Chenming_Hu_2010" role="doc-biblioref">Hu 2010</a>)</span>.</p>
</section>
</section>
<section id="sec-gmid-method" class="level2">
<h2 class="anchored" data-anchor-id="sec-gmid-method">Transistor Sizing Using gm/ID Methodology</h2>
<p>When designing integrated circuits it is an important question how to select various parameters of a MOSFET, like <span class="math inline">\(W\)</span>, <span class="math inline">\(L\)</span>, or the bias current <span class="math inline">\(I_\mathrm{D}\)</span>. In comparison to using discrete components in PCB design, or also compared to a bipolar junction transistor (BJT), we have these degrees of freedom, which make integrated circuit design so interesting.</p>
<p>Often, transistor sizing in entry-level courses is based on the square-law model, where a simple analytical equation for the drain current can be derived. However, in nanometer CMOS, the MOSFET behaviour is much more complex than these simple models. Also, this highly simplified derivations introduce concepts like the threshold voltage or the overdrive voltage, which are interesting from a theoretical viewpoint, but bear little practical use.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>One of the many simplifactions of the square-law model is that the mobility of the charge carriers is assumed constant (it is not). Further, the existance of a threshold voltage is assumed, but in fact this voltage is just existing given a certain definition, and depending on definition, its value changed. In addition, in nm CMOS, the threshold voltage is a function on many thing, like <span class="math inline">\(W\)</span> and <span class="math inline">\(L\)</span>.</p>
</div>
</div>
<p>An additional shortcoming of the square-law model is that it is only valid in strong inversion, i.e.&nbsp;for large <span class="math inline">\(V_\mathrm{GS}\)</span> where the drain current is dominated by the drift current. As soon as the gate-source voltage gets smaller, the square-law model breaks, as the drain current component based on diffusion currents gets dominant. Modern compact MOSFET models (like the PSP model used in SG13G2) use hundreds of parameters and fairly complex equations to somewhat properly describe MOSFET behaviour over a wide range of parameters like <span class="math inline">\(W\)</span>, <span class="math inline">\(L\)</span>, and temperature. A modern approach to MOSFET sizing is thus based on the thought to use exactly these MOSFET models, characterize them, put the resulting data into tables and charts, and thus learn about the complext MOSFET behaviour and use it for MOSFET sizing.</p>
<p>Being a well-established approach we select the <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> methodology introduced by P. Jespers and B. Murmann in <span class="citation" data-cites="Jespers_Murmann_2017">(<a href="#ref-Jespers_Murmann_2017" role="doc-biblioref">Jespers and Murmann 2017</a>)</span>. A brief introduction is available <a href="https://github.com/iic-jku/analog-circuit-design/blob/main/sizing/Ref_Murmann_gmID.pdf">here</a> as well.</p>
<p>The <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> methodology has the huge advantage that is catches MOSFET behavior quite accurately over a wide range of operating conditions, and the curves look very similar for pretty much all CMOS technologies, form micrometer bulk CMOS down to nanometer FinFET devices. Of course the absolute values change, but the method applies universally.</p>
<section id="mosfet-characterization-testbench" class="level3">
<h3 class="anchored" data-anchor-id="mosfet-characterization-testbench">MOSFET Characterization Testbench</h3>
<p>In order to get the required tabulated data we use a testbench in Xschem which sweeps the terminal voltages, and records various large- and small-signal parameters, which are then stored in large tables. The testbench for the LV NMOS is shown in <a href="#fig-techsweep-nmos-tb" class="quarto-xref">Figure&nbsp;6</a>, and the TB for the LV PMOS is shown in <a href="#fig-techsweep-pmos-tb" class="quarto-xref">Figure&nbsp;7</a>.</p>
<div id="fig-techsweep-nmos-tb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-techsweep-nmos-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./xschem/techsweep_sg13g2_lv_nmos.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6: Testbench for LV NMOS g_\mathrm{m}/I_\mathrm{D} characterization."><img src="./xschem/techsweep_sg13g2_lv_nmos.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-techsweep-nmos-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Testbench for LV NMOS <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> characterization.
</figcaption>
</figure>
</div>
<div id="fig-techsweep-pmos-tb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-techsweep-pmos-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./xschem/techsweep_sg13g2_lv_pmos.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7: Testbench for LV PMOS g_\mathrm{m}/I_\mathrm{D} characterization."><img src="./xschem/techsweep_sg13g2_lv_pmos.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-techsweep-pmos-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Testbench for LV PMOS <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> characterization.
</figcaption>
</figure>
</div>
<p>We will use Jupyter notebooks to inspect the resulting data, and interpret some important graphs. This will greatly help to understand the MOSFET behaviour.</p>
</section>
<section id="sec-techsweep-nmos" class="level3">
<h3 class="anchored" data-anchor-id="sec-techsweep-nmos">NMOS Characterization</h3>
<p>First, we will start looking at the LV NMOS. In <a href="#sec-techsweep-pmos" class="quarto-xref">Section&nbsp;3.3</a> we have the corresponding graphs for the LV PMOS. In this lecture, we will only use the LV MOSFETs. While there are also the HV types available, they are mainly used for high-voltage circuits, like circuits connecting to the outside world. Here, we only will design low-voltage circuits running at a nominal supply voltage of <span class="math inline">\(1.5\,\text{V}\)</span>, so only the LV types are of interest to us.</p>
<p>The first import graph is the plot of <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(f_\mathrm{T}\)</span> versus the gate-source voltage <span class="math inline">\(V_\mathrm{GS}\)</span>. First let us answer the question why <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> is a good parameter to look at, and actually this is also the central parameter in the <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> methodology. In many circuits that are biased in class-A (i.e., with a constant quiescent current that is larger than the largest signal excursion, see <a href="https://en.wikipedia.org/wiki/Power_amplifier_classes#Class_A">biasing</a>) we want to get a large amplification from a MOSFET, which corresponds to a large <span class="math inline">\(g_\mathrm{m}\)</span>. We want this by spending the minimum biasing current possible (ideally zero), as we always design for minimum power consumption. Thus, a high <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> ratio is good.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Designing for minimum power consumption is pretty much always mandated. For battery-operated equipment it is a paramount requirement, but also in other equipment electrical energy consumption is a concern, and often severly limited by the cooling capabilities of the electrical system.</p>
</div>
</div>
<p>However, as can be seen in the below plot, there exists a strong and unfortunate trade-off with device speed, characterized here by the transit frequency <span class="math inline">\(f_\mathrm{T}\)</span>. It would be ideal if there exists a design point where we get high transconductance per bias current concurrently to having the fastest operation, but unfortunately, this is clearly not the case. The <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> peaks for <span class="math inline">\(V_\mathrm{GS}&lt; 0.3\,\text{V}\)</span>, and the highest speed we get at <span class="math inline">\(V_\mathrm{GS}\approx 1.2\,\text{V}\)</span>. The dashed vertical line plots the nominal threshold voltage, as you can see in this continuum of parameter space, it marks not a particularly special point.</p>
<p>Note that <span id="eq-mosfet-gmid-weakinversion"><span class="math display">\[
\frac{g_\mathrm{m}}{I_\mathrm{D}} = \frac{1}{n V_\mathrm{T}}
\tag{1}\]</span></span> for a MOSFET in weak inversion (i.e., small gate-source voltage). <span class="math inline">\(n\)</span> is the subthreshold slope, and <span class="math inline">\(V_\mathrm{T} = k T / q\)</span> which is <span class="math inline">\(25.8\,\text{mV}\)</span> at <span class="math inline">\(300\,\text{K}\)</span>. We thus have <span class="math inline">\(n \approx 1.38\)</span> for this LV NMOS, which falls nicely into the usual range for <span class="math inline">\(n\)</span> of <span class="math inline">\(1.3\)</span> to <span class="math inline">\(1.5\)</span> for bulk CMOS (FinFET have <span class="math inline">\(n\)</span> very close to <span class="math inline">\(1\)</span>).</p>
<p>For the classical square-law model of the MOSFET in strong inversion, <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> is given as <span id="eq-mosfet-gmid-stronginversion"><span class="math display">\[
\frac{g_\mathrm{m}}{I_\mathrm{D}} = \frac{2}{V_\mathrm{GS}- V_\mathrm{th}} = \frac{2}{V_\mathrm{od}}
\tag{2}\]</span></span> with <span class="math inline">\(V_\mathrm{th}\)</span> the threshold voltage and <span class="math inline">\(V_\mathrm{od}\)</span> the so-called “overdrive voltage.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why are we so often using <span class="math inline">\(300\,\text{K}\)</span> for a typical condition? As this corresponds to roughly <span class="math inline">\(27^{\circ}\text{C}\)</span>, this accounts for some self heating compared to otherwise usual room temperatures. Further, engineers like round numbers which are easy to remember, so <span class="math inline">\(300\,\text{K}\)</span> is used as a proxy for room temperature.</p>
</div>
</div>
<p>As we can also see from belows plot, the peak transit frequency of the LV NMOS is about <span class="math inline">\(75\,\text{GHz}\)</span>, which allows building radio-frequency circuits up to ca. <span class="math inline">\(f_\mathrm{T} / 10 = 7.5\,\text{GHz}\)</span>, which is a respectible number. It is no coincidence, that the transition for RF design in the GHz-range switched from BJT-based technologies to CMOS roughly in the timeframe when 130nm CMOS became available (ca. 2000).</p>
<div class="quarto-embed-nb-cell">
<div id="cell-5" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.151250Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:07.778457Z&quot;}" data-tags="[&quot;fig-nmos-gmid-ft-vs-vgs&quot;]" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-6-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-6-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>The following figure plots <span class="math inline">\(f_\mathrm{T}\)</span> against <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> for several different <span class="math inline">\(L\)</span>. As you can see, device speeds maximizes for a low <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and a short <span class="math inline">\(L\)</span>. As you can see the drain-source voltage is kept at <span class="math inline">\(V_\mathrm{DS}= 0.75\,\text{V} = V_\mathrm{DD}/ 2\)</span>, which is a typical value keeping the MOSFET in saturation across the characterization sweeps. Further, the source-bulk voltage is kept at <span class="math inline">\(V_\mathrm{SB} = 0\,\text{V}\)</span>, which means bulk and source terminals are connected.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-8" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.636920Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.496476Z&quot;}" data-tags="[&quot;fig-nmos-ft-vs-gmid-vs-l&quot;]" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-9-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-9-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>The next plot shows the ratio of <span class="math inline">\(g_\mathrm{m}/ g_\mathrm{ds}\)</span> versus <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span>. The ratio <span class="math inline">\(g_\mathrm{m}/ g_\mathrm{ds}\)</span> is the so-called <strong>“self-gain”</strong> of the MOSFET, and shows the maximum voltage gain we can achieve in a single transistor configuration. As one can see the self gain increases for increasing <span class="math inline">\(L\)</span>, but this also gives a slower transistor, so again there is a trade-off. This plot allows us to select the proper <span class="math inline">\(L\)</span> of a MOSFET if we know which amount of self gain we need.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-9" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.758497Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.637839Z&quot;}" data-tags="[&quot;fig-nmos-gmgds-vs-gmid-vs-l&quot;]" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-10-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-10-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>The following figure plots the drain current density <span class="math inline">\(I_\mathrm{D}/W\)</span> as a function of <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(L\)</span>. With this plot we can find out how to set the <span class="math inline">\(W\)</span> of a MOSFET once we know the biasing current <span class="math inline">\(I_\mathrm{D}\)</span>, the <span class="math inline">\(L\)</span> (selected according to self gain, <span class="math inline">\(f_\mathrm{T}\)</span>, and other considerations) and the <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> design point we selected. The drain current density <span class="math inline">\(I_\mathrm{D}/W\)</span> is a very useful nomalized metric to use, because the physical action in the MOSFET establishes a charge density in the channel below the gate, and the changing of the <span class="math inline">\(W\)</span> of the device merely transforms this charge density into an absolute parameter (together with <span class="math inline">\(L\)</span>).</p>
<div class="quarto-embed-nb-cell">
<div id="cell-10" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.963903Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.759239Z&quot;}" data-tags="[&quot;fig-nmos-jd-vs-gmid-vs-l&quot;]" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-11-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-11-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>The following plot shows the minimum drain-source voltage <span class="math inline">\(V_\mathrm{ds,sat}\)</span> that we need to establish in order to keep the MOSFET in saturation. As you can see, this value is almost independent of <span class="math inline">\(L\)</span>, and increases for small <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span>. So for low-voltage circuits, where headroom is precious, we tend to bias at <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\ge 10\)</span>, wheres for fast circuits we need to go to small <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\le 5\)</span> requiring substantial voltage headroom per MOSFET stage that we stack on top of each other.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-11" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:09.074153Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.964633Z&quot;}" data-tags="[&quot;fig-nmos-vdsat-vs-gmid-vs-l&quot;]" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-12-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-12-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>For analog circuits the noise performance is usually quite important. Thermal noise of a resistor (the Johnson-Nyquist noise) has a flat power-spectral density (PSD) given by <span class="math inline">\(\overline{V_\mathrm{n}^2}/\Delta f = 4 k T R\)</span>, where <span class="math inline">\(k\)</span> is Boltzmann’s constant, <span class="math inline">\(T\)</span> absolute temperature, and <span class="math inline">\(R\)</span> the value of the resistor (the unit of <span class="math inline">\(\overline{V_\mathrm{n}^2}/df\)</span> is <span class="math inline">\(\text{V}^2/\text{Hz}\)</span>). This PSD is essentially flat until very high frequencies where <a href="https://en.wikipedia.org/wiki/Johnson–Nyquist_noise">quantum effects</a> start to kick in.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We usually leave the <span class="math inline">\(\Delta f\)</span> away for a shorter notation, so we write <span class="math inline">\(\overline{V_\mathrm{n}^2}\)</span> when we actually mean <span class="math inline">\(\overline{V_\mathrm{n}^2}/\Delta f\)</span>.</p>
<p>Please also note that the pair of <span class="math inline">\(k T\)</span> pretty much always shows up together, so when you do a calculation and you miss the one or the other, that is often a sign for miscalculation.</p>
<p>Fuerther, when working with PSD there is the usage of a one-sided (<span class="math inline">\(f\)</span> runs from <span class="math inline">\(0\)</span> to <span class="math inline">\(\infty\)</span>) or two-sided PSD (<span class="math inline">\(f\)</span> runs from <span class="math inline">\(-\infty\)</span> to <span class="math inline">\(\infty\)</span>). The default in this lecture is the usage of a <strong>one-sided PSD</strong>.</p>
</div>
</div>
<p>In this lecture the only MOSFET noise we consider is the drain noise, showing up as a current noise between drain and source, and given by <span id="eq-mosfet-noise"><span class="math display">\[
\overline{I_\mathrm{d,n}^2} = 4 k T \gamma g_\mathrm{d0}
\tag{3}\]</span></span> In saturation (the MOSFET operating as a current source), <span class="math inline">\(g_\mathrm{d0} = g_\mathrm{m}\)</span>, whereas in triode (the MOSFET operating as a switch), <span class="math inline">\(g_\mathrm{d0} = g_\mathrm{ds}\)</span>.</p>
<p>The factor <span class="math inline">\(\gamma\)</span> is a function of many things (in classical theory, <span class="math inline">\(\gamma = 2/3\)</span> in saturation and <span class="math inline">\(\gamma = 1\)</span> in triode), and it is characterized in the following plot as a function of <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(L\)</span>. So when calculating MOSFET noise we can lookup <span class="math inline">\(\gamma\)</span> in the below plot, and use <a href="#eq-mosfet-noise" class="quarto-xref">Equation&nbsp;3</a> to calculate the effective drain current noise.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-12" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:09.243573Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:09.074949Z&quot;}" data-tags="[&quot;fig-nmos-gamma-vs-gmid-vs-l&quot;]" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-13-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-13-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>In a MOSFET, unfortunately, besides the thermal noise according to <a href="#eq-mosfet-noise" class="quarto-xref">Equation&nbsp;3</a>, there is also a substantial low-frequency excess noise, called “flicker noise” due to its characteristic <span class="math inline">\(\overline{I_\mathrm{d,nf}^2} = K_\mathrm{f}/f\)</span> behaviour (this means that this noise PSD decreases versus frequency). In order to characterize this flicker noise the following plot shows the cross-over frequency <span class="math inline">\(f_\mathrm{co}\)</span>, where the flicker noise is as large as the thermal noise. As can be seen in the below plot, this frequency is a strong function of <span class="math inline">\(L\)</span> and <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span>. Generally, the flicker noise is proportional to <span class="math inline">\((W L)^{-1}\)</span>, so the larger the device is, the lower the flicker noise. The parameter <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> largely stays constant when we keep <span class="math inline">\(W/L\)</span> constant, so for a given <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> flicker noise is proportinal to <span class="math inline">\(1/L^2\)</span>. However, increasing <span class="math inline">\(L\)</span> lowers device speed dramatically, so here we have a trade-off between flicker-noise performance and MOSFET speed, and this can have dramatic consequences for high-speed circuits.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The physical origin of flicker noise is the crystal interface between silicon (Si) and the silicondioxide (SiO<sub>2</sub>). Since these are different materials, there are dangling bonds, which can capture charge charriers travelling in the channel. After a random time, these carriers are released, and flicker noise is the result. The amount of flicker noise is a function of the manufacturing process, and will generally be different between device types and wafer foundries.</p>
</div>
</div>
<p>As you can see in the following plot, <span class="math inline">\(f_\mathrm{co}\)</span> can reach well into the 10’s of MHz for short MOSFETs, significantly degrading the noise performance of a circuit.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-13" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:09.478093Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:09.244904Z&quot;}" data-tags="[&quot;fig-nmos-fco-vs-gmid-vs-l&quot;]" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-14-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_nmos-cell-14-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="sec-techsweep-pmos" class="level3">
<h3 class="anchored" data-anchor-id="sec-techsweep-pmos">PMOS Characterization</h3>
<p>In the following, we have the same plots as discussed in <a href="#sec-techsweep-nmos" class="quarto-xref">Section&nbsp;3.2</a>, but now for the PMOS.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In all PMOS plots we plot positive values for voltages and currents, to have compatible plots to the NMOS. Of course, in a PMOS, voltages and currents have different polarity compared to the PMOS.</p>
</div>
</div>
<p><span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(f_\mathrm{T}\)</span> versus the gate-source voltage <span class="math inline">\(V_\mathrm{GS}\)</span>:</p>
<div class="quarto-embed-nb-cell">
<div id="cell-5" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.151250Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:07.778457Z&quot;}" data-tags="[&quot;fig-pmos-gmid-ft-vs-vgs&quot;]" data-execution_count="5">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-6-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-6-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(f_\mathrm{T}\)</span> against <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> for several different <span class="math inline">\(L\)</span>. One can see significantly lower top speed for the PMOS compared to the NMOS, which means for high-speed circuits the NMOS should be used.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-8" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.636920Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.496476Z&quot;}" data-tags="[&quot;fig-pmos-ft-vs-gmid-vs-l&quot;]" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-9-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-9-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p><span class="math inline">\(g_\mathrm{m}/ g_\mathrm{ds}\)</span> versus <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span>. Unfortunately, one can see a modelling error for the PMOS in this plot. The self gain <span class="math inline">\(g_\mathrm{m}/ g_\mathrm{ds}\)</span> reaches non-physical values, which indicates an issue with the <span class="math inline">\(g_\mathrm{ds}\)</span> modelling for the PMOS. We can not use these values for our circuit sizing, so we will use the respective NMOS plots also for the PMOS.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>This example shows how important it is to benchmark the device models when starting to use a new technology. Modelling artifacts like the one shown are quite often happening, as setting up the device compact models and parametrizing them according to measurement data is a very complex task. In any case, just be aware that modelling issues could exist in whatever PDK you are using!</p>
</div>
</div>
<div class="quarto-embed-nb-cell">
<div id="cell-9" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.758497Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.637839Z&quot;}" data-tags="[&quot;fig-pmos-gmgds-vs-gmid-vs-l&quot;]" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-10-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-10-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>Drain current density <span class="math inline">\(I_\mathrm{D}/W\)</span> as a function of <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(L\)</span>:</p>
<div class="quarto-embed-nb-cell">
<div id="cell-10" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:08.963903Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.759239Z&quot;}" data-tags="[&quot;fig-pmos-jd-vs-gmid-vs-l&quot;]" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-11-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-11-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>Minimum drain-source voltage <span class="math inline">\(V_\mathrm{ds,sat}\)</span> versus <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(L\)</span>:</p>
<div class="quarto-embed-nb-cell">
<div id="cell-11" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:09.074153Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:08.964633Z&quot;}" data-tags="[&quot;fig-pmos-vdsat-vs-gmid-vs-l&quot;]" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-12-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-12-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>Noise factor <span class="math inline">\(\gamma\)</span> versus <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(L\)</span>:</p>
<div class="quarto-embed-nb-cell">
<div id="cell-12" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:09.243573Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:09.074949Z&quot;}" data-tags="[&quot;fig-pmos-gamma-vs-gmid-vs-l&quot;]" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-13-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-13-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
<p>Flicker noise corner frequency <span class="math inline">\(f_\mathrm{co}\)</span> versus <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> and <span class="math inline">\(L\)</span>. If you compare this figure carefully with the NMOS figure you can see that for some operating points the flicker noise for the PMOS is lower than for the NMOS. This is often true for CMOS technologies, so it can be an advantage to use a PMOS transistor in places where flicker noise is critical, like an OTA input stage. Using PMOS has the further advantage that the bulk node can be tied to source (which for NMOS is only possible in a triple-well technology, which is often not available), which gets rid of the <a href="https://en.wikipedia.org/wiki/Threshold_voltage">body effect</a>.</p>
<div class="quarto-embed-nb-cell">
<div id="cell-13" class="cell" data-executetime="{&quot;end_time&quot;:&quot;2024-08-02T08:03:09.478093Z&quot;,&quot;start_time&quot;:&quot;2024-08-02T08:03:09.244904Z&quot;}" data-tags="[&quot;fig-pmos-fco-vs-gmid-vs-l&quot;]" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-14-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21"><img src="index_files/figure-html/.-sizing-techsweep_sg13_plots_pmos-cell-14-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sec-mosfet-diode" class="level2">
<h2 class="anchored" data-anchor-id="sec-mosfet-diode">First Circuit: MOSFET Diode</h2>
<p>The first (simple) circuit we will investigate is a MOSFET, where the gate is shorted with a drain, a so-called MOSFET “diode”, which is shown in <a href="#fig-mosfet-diode" class="quarto-xref">Figure&nbsp;8</a>. This diode is one half of a current mirror, which we will investigate in a future section.</p>
<div id="cell-fig-mosfet-diode" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-mosfet-diode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-mosfet-diode-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Figure&nbsp;8: A MOSFET connected as a diode."><img src="index_files/figure-html/fig-mosfet-diode-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: A MOSFET connected as a diode.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Why looking at a single-transistor circuit at all? By starting with the simplest possible circuit we can develop important skills in circuit analysis (setting up and calculating a small-signal model, calculating open-loop gain, calculate noise) and Xschem/ngspice simulation testbench creation. We safely assume that also the Mona Lisa was not Leonardo da Vinci’s first painting, so let’s start slow.</p>
<p>This diode is usually biased by a current source, shown as <span class="math inline">\(I_\mathrm{bias}\)</span> in the figure. Depending on MOSFET sizing with <span class="math inline">\(W\)</span> and <span class="math inline">\(L\)</span>, a certain gate-source voltage <span class="math inline">\(V_\mathrm{GS}\)</span> will develop. This voltage can be used as a biasing voltage for other circuit parts, for example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is important to realize that this configuration essentially employs a feedback loop for operation. The voltage at the drain of the MOSFET is sensed by the gate, and the gate voltage changes until the <span class="math inline">\(I_\mathrm{D}\)</span> is exactly equal to <span class="math inline">\(I_\mathrm{bias}\)</span>. In this sense this is probably the smallest feedback circuit one can build.</p>
</div>
</div>
<section id="mosfet-diode-sizing" class="level3">
<h3 class="anchored" data-anchor-id="mosfet-diode-sizing">MOSFET Diode Sizing</h3>
<p>We will now build this circuit in Xschem. For sizing the MOSFET we will use the <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> methodology introduced in <a href="#sec-gmid-method" class="quarto-xref">Section&nbsp;3</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please build a MOSFET diode circuit in Xschem where you use an LV NMOS, set <span class="math inline">\(I_\mathrm{bias} = 20\,\mu\text{A}\)</span>, <span class="math inline">\(L = 0.13\,\mu\text{m}\)</span>, and we want to use <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}= 10\)</span> (often a suitable compromise between transistor speed and <span class="math inline">\(g_\mathrm{m}\)</span> efficiency).</p>
<ol type="1">
<li>Use the figures in <a href="#sec-techsweep-nmos" class="quarto-xref">Section&nbsp;3.2</a> to find out the proper value for <span class="math inline">\(W\)</span>.</li>
<li>What is <span class="math inline">\(f_\mathrm{T}\)</span> for this MOSFET? What is the value for <span class="math inline">\(g_\mathrm{m}\)</span> and <span class="math inline">\(g_\mathrm{ds}\)</span>?</li>
<li>Draw the circuit in Xschem, and simulate the operating point. Do the values match to the values found out before during circuit sizing?</li>
</ol>
</div>
</div>
<p>Before continuing, please finish the previous exercise. Once you are done, compare with the below provided solution.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Using the fact that <span class="math inline">\(I_\mathrm{bias} = I_\mathrm{D} = 20\,\mu\text{A}\)</span> and <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}= 10\)</span> directly provides <span class="math inline">\(g_\mathrm{m}= 0.2\,\text{mS}\)</span>.</li>
<li>Using the self-gain plot, we see that <span class="math inline">\(g_\mathrm{m}/g_\mathrm{ds}\approx 21\)</span>, so <span class="math inline">\(g_\mathrm{ds}\approx 9.5\,\mu\text{S}\)</span>. The <span class="math inline">\(f_\mathrm{T}\)</span> can easily be found in the respective plot to be <span class="math inline">\(f_\mathrm{T} = 23\,\text{GHz}\)</span>.</li>
<li>The <span class="math inline">\(W\)</span> of the MOSFET we find using the drain current density plot and the given bias current. Rounding to half-microns results in <span class="math inline">\(W = 1\,\mu\text{m}\)</span>.</li>
<li>Since we are looking at the graphs, we further find <span class="math inline">\(\gamma = 0.84\)</span>, <span class="math inline">\(V_\mathrm{ds,sat} = 0.18\,\text{V}\)</span>, and <span class="math inline">\(f_\mathrm{co} \approx 15\,\text{MHz}\)</span>.</li>
<li>In addition, we expect <span class="math inline">\(V_\mathrm{GS}\approx 0.6\,\text{V}\)</span>.</li>
</ol>
<p>An example Jupyter notebook to extract these values accurately you can find <a href="./sizing/sizing_mosfet_diode-preview.html">here</a>. An Xschem schematic for this exercise is provide <a href="./xschem/mosfet_diode_sizing.sch">as well</a>.</p>
</div>
</div>
</section>
<section id="mosfet-diode-large-signal-behaviour" class="level3">
<h3 class="anchored" data-anchor-id="mosfet-diode-large-signal-behaviour">MOSFET Diode Large-Signal Behaviour</h3>
<p>As discussed above, the MOSFET diode configuration is essentially a feedback loop. Before we will analyse this loop in small-signal, we want to investgate how this loop settles in the time domain, and by doing this we can observe the large-signal settling behaviour. To simulate this, we change the dc bias source from the previous example to a transient current source, which we will turn on after some ns. The resulting Xschem testbench is shown in <a href="#fig-mosfet-diode-settling-tb" class="quarto-xref">Figure&nbsp;9</a>.</p>
<div id="fig-mosfet-diode-settling-tb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-settling-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./xschem/mosfet_diode_settling.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="Figure&nbsp;9: Testbench for MOSFET diode transient settling."><img src="./xschem/mosfet_diode_settling.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-settling-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Testbench for MOSFET diode transient settling.
</figcaption>
</figure>
</div>
<p>In <a href="#fig-mosfet-diode-settling-tb" class="quarto-xref">Figure&nbsp;9</a> another interesting effect can be observed: While the turn-on happens quite rapidly (essentially the bias current source charges the gate capacitance, until the gate-source voltage is large enough that the drain current counteracts the bias current), the turn-off shows a very long settling tail. This is due to the fact that as the gate capacitance is discharged by the drain current the <span class="math inline">\(V_\mathrm{GS}\)</span> drops, which in turn reduces the drain current, which will make the discharge even slower. We have an effect similar to the capacitor discharge by a diode <span class="citation" data-cites="Hellen_2003">(<a href="#ref-Hellen_2003" role="doc-biblioref">Hellen 2003</a>)</span>.</p>
<p>It is thus generally a good idea to add power-down switches to the circuits to disable the circuit quickly by pulling floating nodes to a defined potential (usually <span class="math inline">\(V_\mathrm{DD}\)</span> or <span class="math inline">\(V_\mathrm{SS}\)</span>) and to avoid long intermediate states during power down. This will also allow a turn-on from a well-defined off-state.</p>
</section>
<section id="mosfet-diode-small-signal-analysis" class="level3">
<h3 class="anchored" data-anchor-id="mosfet-diode-small-signal-analysis">MOSFET Diode Small-Signal Analysis</h3>
<p>We now want to investigate the small-signal behaviour of the MOSFET diode. Based on the small-signal model of the MOSFET in <a href="#fig-mosfet-small-signal-model" class="quarto-xref">Figure&nbsp;5</a> we realize that gate and drain are shorted, and we also connect bulk to source. We can thus simplify the circit to the one shown in <a href="#fig-mosfet-diode-small-signal" class="quarto-xref">Figure&nbsp;10</a>.</p>
<div id="cell-fig-mosfet-diode-small-signal" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-mosfet-diode-small-signal" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-small-signal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-mosfet-diode-small-signal-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="Figure&nbsp;10: The MOSFET diode small-signal model."><img src="index_files/figure-html/fig-mosfet-diode-small-signal-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-small-signal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: The MOSFET diode small-signal model.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For small-signal analysis we would not need to declare one node as the ground potential. However, when doing so, and selecting the ground node strategically, we can simplify the analysis, as we usually do not formulate KCL for the ground node (as we have only <span class="math inline">\(N-1\)</span> independent KCL equations, <span class="math inline">\(N\)</span> being the number of nodes of a circuit), and the potential difference equations are simpler if one node is at <span class="math inline">\(0\,V\)</span>.</p>
</div>
</div>
<p>For calculating the small-signal impedance of the MOSFET diode we formulate KCL at the top node to get <span class="math display">\[
i_\mathrm{bias} - s C_\mathrm{gs}v_\mathrm{gs}- g_\mathrm{m}v_\mathrm{gs}- g_\mathrm{ds}v_\mathrm{gs}= 0.
\]</span></p>
<p>It follows that <span id="eq-mosfet-diode-impedance"><span class="math display">\[
Z_\mathrm{diode}(s) = \frac{v_\mathrm{gs}}{i_\mathrm{bias}} = \frac{1}{g_\mathrm{m}+ g_\mathrm{ds}+ s C_\mathrm{gs}}.
\tag{4}\]</span></span></p>
<p>When neglecting <span class="math inline">\(g_\mathrm{ds}\)</span> and at dc we get <span class="math inline">\(Z_\mathrm{diode} = 1 / g_\mathrm{m}\)</span>, which is an important result and should be memorized.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>In circuit analysis it is often algebraically easier to work with conductances instead of impedances, so please remember that Ohm’s law for a conductance is <span class="math inline">\(I = G U\)</span>, and for a capacitance is <span class="math inline">\(I = s C U\)</span>. When writing equations, it is also practical to keep <span class="math inline">\(s C\)</span> together, so we will strive to sort terms accordingly.</p>
</div>
</div>
<p>Looking at <a href="#eq-mosfet-diode-impedance" class="quarto-xref">Equation&nbsp;4</a> we see that for low frequencies, the diode impedance is resistive, and for high frequencies it becomes capactive as the gate-source capacitance starts to dominate. The corner frequeny of this low-pass can be calculated as <span class="math display">\[
\omega_\mathrm{c} = \frac{g_\mathrm{m}+ g_\mathrm{ds}}{C_\mathrm{gs}} \approx \omega_\mathrm{T}
\]</span> which is pretty much the transit frequency of the MOSFET!</p>
</section>
<section id="mosfet-diode-stability-analysis" class="level3">
<h3 class="anchored" data-anchor-id="mosfet-diode-stability-analysis">MOSFET Diode Stability Analysis</h3>
<p>The diode-connected MOSFET forms a feedback loop. What is the open-loop gain? For calculating it, we are breaking the loop, and apply a dummy <span class="math inline">\(C_\mathrm{gs}^{*}\)</span> at the right side to keep the impedances correct. A circuit diagram is shown in <a href="#fig-mosfet-diode-openloop" class="quarto-xref">Figure&nbsp;11</a>, we break the loop at the dotted connection. As we can see in this example, it is critically important when breaking up a loop for analysis (also for simulation!) to keep the terminal impedances the same. Only in special cases where the load impedance is very high or the driving impedance is very low is it acceptable to disregard loading effects!</p>
<div id="cell-fig-mosfet-diode-openloop" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-mosfet-diode-openloop" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-openloop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-mosfet-diode-openloop-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-25" title="Figure&nbsp;11: The MOSFET diode small-signal circuit for open-loop analysis."><img src="index_files/figure-html/fig-mosfet-diode-openloop-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-openloop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: The MOSFET diode small-signal circuit for open-loop analysis.
</figcaption>
</figure>
</div>
</div>
</div>
<p>By inspecting <a href="#fig-mosfet-diode-openloop" class="quarto-xref">Figure&nbsp;11</a> we see that <span class="math display">\[
v_\mathrm{out} = - g_\mathrm{m}v_\mathrm{in} \frac{1}{g_\mathrm{ds}+ s C_\mathrm{gs}}.
\]</span></p>
<p>The open-loop gain <span class="math inline">\(H_\mathrm{ol}(s)\)</span> is thus <span id="eq-mosfet-diode-openloop-gain"><span class="math display">\[
H_\mathrm{ol}(s) = \frac{v_\mathrm{out}}{v_\mathrm{in}} = -\frac{g_\mathrm{m}}{g_\mathrm{ds}+ s C_\mathrm{gs}}.
\tag{5}\]</span></span></p>
<p>Inspecting <a href="#eq-mosfet-diode-openloop-gain" class="quarto-xref">Equation&nbsp;5</a> we realize that</p>
<ol type="1">
<li>the dc gain <span class="math inline">\(g_\mathrm{m}/ g_\mathrm{ds}\)</span> is the self-gain of the MOSFET, so <span class="math inline">\(20 \log(0.2 \cdot 10^{-3} / 9.6 \cdot 10 ^{-6}) = 26.4\,\text{dB}\)</span>, and</li>
<li>there is a pole at <span class="math inline">\(\omega_\mathrm{p} = -g_\mathrm{ds}/ C_\mathrm{gs}\)</span>, which is at <span class="math inline">\(9.6 \cdot 10 ^{-6} / (2 \pi \cdot 1.4 \cdot 10^{-15}) = 1.1\,\text{GHz}\)</span>.</li>
</ol>
<p>With this single pole location in <span class="math inline">\(H_\mathrm{ol}(s)\)</span> this loop is perfectly stable at under all conditions.</p>
<p>The question is now how to simulate this open-loop gain, and how to break the loop open in simulation? In general there are various methods, as we can use artificially large (ideal) inductors and capacitors to break loops open and still establish the correct dc operating points for the ac loop analysis. However, mimicking the correct loading can be an issue, and requires a lot of careful consideration. There is an alternative method which breaks the loop open only by adding an ac voltage source in series (thus keeps the dc operating point intact), or injects current using a current source. Based on both measurements the open-loop gain can be calculated. This is called <strong>Middlebrook’s method</strong> <span class="citation" data-cites="Middlebrook_1975">(<a href="#ref-Middlebrook_1975" role="doc-biblioref">Middlebrook 1975</a>)</span> which is based on double injection, and we will use it for our loop simulations.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Middlebrook's Method">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Middlebrook’s Method
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we want to do an open-loop gain analysis, we break the loop at one point by inserting (1) an ac voltage source, and (2) attach an ac current source, as shown in <a href="#fig-middlebrook-voltage" class="quarto-xref">Figure&nbsp;12</a> and <a href="#fig-middlebrook-current" class="quarto-xref">Figure&nbsp;13</a>.</p>
</div>
</div>
<div id="cell-fig-middlebrook-voltage" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-middlebrook-voltage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-middlebrook-voltage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-middlebrook-voltage-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-26" title="Figure&nbsp;12: Middlebrook voltage loop gain simulation."><img src="index_files/figure-html/fig-middlebrook-voltage-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-middlebrook-voltage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Middlebrook voltage loop gain simulation.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-middlebrook-current" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div id="fig-middlebrook-current" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-middlebrook-current-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-middlebrook-current-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-27" title="Figure&nbsp;13: Middlebrook current loop gain simulation."><img src="index_files/figure-html/fig-middlebrook-current-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-middlebrook-current-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Middlebrook current loop gain simulation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For both cases we do an ac analysis, and find the corresponding transfer functions <span class="math inline">\(T_\mathrm{v}\)</span> and <span class="math inline">\(T_\mathrm{i}\)</span>: <span class="math display">\[
T_\mathrm{v} = -\frac{V_\mathrm{r}}{V_\mathrm{f}}
\]</span> and <span class="math display">\[
T_\mathrm{i} = -\frac{I_\mathrm{r}}{I_\mathrm{f}}
\]</span></p>
<p>Then, we can calculate the closed-loop transfer function <span class="math inline">\(T(s) = H_\mathrm{ol(s)}\)</span> as <span class="math display">\[
T(s) = \frac{T_\mathrm{v} T_\mathrm{i} - 1}{T_\mathrm{v} + T_\mathrm{i} + 2}
\]</span></p>
<p>We now want to simulate the open-loop transfer function <span class="math inline">\(H_\mathrm{ol}(s)\)</span> by using Middlebrook’s method and confirm our analysis above.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please build a simulation testbench in Xschem to simulate the open-loop transfer function of the MOSFET diode. Confirm the dc gain and pole location as given by <a href="#eq-mosfet-diode-openloop-gain" class="quarto-xref">Equation&nbsp;5</a>.</p>
<p>If you are getting stuck you can look at this Xschem <a href="./xschem/mosfet_diode_loopgain.sch">testbench</a>, shown in <a href="#fig-mosfet-diode-loopgain-tb" class="quarto-xref">Figure&nbsp;14</a>.</p>
<div id="fig-mosfet-diode-loopgain-tb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-loopgain-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./xschem/mosfet_diode_loopgain.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="Figure&nbsp;14: Testbench for MOSFET diode stability analysis."><img src="./xschem/mosfet_diode_loopgain.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-loopgain-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Testbench for MOSFET diode stability analysis.
</figcaption>
</figure>
</div>
</div>
</div>
<p>From simulation we see that the open-loop gain is <span class="math inline">\(24.9\,\text{dB}\)</span> at low frequencies, which matches quite well our prediction of <span class="math inline">\(26.4\,\text{dB}\)</span>. In the Bode plot we see a low-pass with a <span class="math inline">\(-3\,\text{dB}\)</span> corner frequency of <span class="math inline">\(1.4\,\text{GHz}\)</span>, which again is fairly close to our prediction of <span class="math inline">\(1.1\,\text{GHz}\)</span>.</p>
</section>
<section id="mosfet-diode-noise-calculation" class="level3">
<h3 class="anchored" data-anchor-id="mosfet-diode-noise-calculation">MOSFET Diode Noise Calculation</h3>
<p>As a final exercise on the MOSFET diode circuit we want to calculate the output noise when we consider <span class="math inline">\(V_\mathrm{GS}\)</span> the output reference voltage which is created when passing a bias current through the MOSFET diode. The bias current we will assume noiseless.</p>
<p>We will use the small-signal circuit shown in <a href="#fig-mosfet-diode-small-signal-w-noise" class="quarto-xref">Figure&nbsp;15</a>.</p>
<div id="cell-fig-mosfet-diode-small-signal-w-noise" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-mosfet-diode-small-signal-w-noise" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-small-signal-w-noise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-mosfet-diode-small-signal-w-noise-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-29" title="Figure&nbsp;15: The MOSFET diode small-signal model with drain noise source."><img src="index_files/figure-html/fig-mosfet-diode-small-signal-w-noise-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-small-signal-w-noise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: The MOSFET diode small-signal model with drain noise source.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As we have already calculated the small-signal diode impedance in <a href="#eq-mosfet-diode-impedance" class="quarto-xref">Equation&nbsp;4</a> we will use this result, and just note that the drain current noise of the MOSFET flows through this impedance. The noise voltage at <span class="math inline">\(v_\mathrm{gs}\)</span> is this given as <span class="math display">\[
\overline{V_\mathrm{n}^2} = Z_\mathrm{diode}^2 \overline{I_\mathrm{n,d}^2}.
\]</span></p>
<p>The drain current noise of the MOSFET is given as (introduced in @#sec-mosfet-smallsignal-model) <span class="math display">\[
\overline{I_\mathrm{n,d}^2} = 4 k T \gamma g_\mathrm{m}.
\]</span></p>
<p>For low frequencies (ignoring <span class="math inline">\(g_\mathrm{ds}\)</span> and <span class="math inline">\(C_\mathrm{gs}\)</span>) we get <span class="math display">\[
\overline{V_\mathrm{n}^2} = Z_\mathrm{diode}^2 \overline{I_\mathrm{n,d}^2} = \frac{1}{g_\mathrm{m}^2} 4 k T \gamma g_\mathrm{m}= \frac{4 k T \gamma}{g_\mathrm{m}}
\]</span> which is the thermal noise of a resistor of value <span class="math inline">\(1 / g_\mathrm{m}\)</span> enhanced by the factor <span class="math inline">\(\gamma\)</span>.</p>
<p>We now calculate the full equation, and after a bit of algebra arrive at <span id="eq-mosfet-diode-noise-psd"><span class="math display">\[
\overline{V_\mathrm{n}^2}(f) = \frac{4 k T \gamma g_\mathrm{m}}{(g_\mathrm{m}+ g_\mathrm{ds})^2 + (2 \pi f C_\mathrm{gs})^2}.
\tag{6}\]</span></span></p>
<p>If we are interested in the PSD of the noise then <a href="#eq-mosfet-diode-noise-psd" class="quarto-xref">Equation&nbsp;6</a> gives us the result. If we are interested in the rms value (the total noise) we need to integrate this equation.</p>
<div class="callout-info">
<p><span class="math display">\[
\int_0^\infty {\frac{a}{b^2 + (c f)^2} df} = \frac{\pi a}{2 b c}
\]</span></p>
</div>
<p>Using the integral help from the previous info box, we can easily get at <span id="eq-mosfet-diode-noise-rms"><span class="math display">\[
V_\mathrm{n,rms}^2 = \int_0^\infty \overline{V_\mathrm{n}^2}(f) df = \frac{k T \gamma g_\mathrm{m}}{(g_\mathrm{m}+ g_\mathrm{ds}) C_\mathrm{gs}}.
\tag{7}\]</span></span></p>
<p>The form of <a href="#eq-mosfet-diode-noise-rms" class="quarto-xref">Equation&nbsp;7</a> is the exact solution, but we gain additional insight if we assume that <span class="math inline">\(g_\mathrm{m}+ g_\mathrm{ds}\approx g_\mathrm{m}\)</span> and then <span id="eq-mosfet-diode-noise-rms-simplified"><span class="math display">\[
V_\mathrm{n,rms}^2 = \frac{k T \gamma}{C_\mathrm{gs}}.
\tag{8}\]</span></span></p>
<p>Inspecting <a href="#eq-mosfet-diode-noise-rms-simplified" class="quarto-xref">Equation&nbsp;8</a> we see our familiar <span class="math inline">\(kT/C\)</span> noise enhanced by the factor <span class="math inline">\(\gamma\)</span>! Calculating this value for our MOSFET diode we get <span class="math inline">\(\sqrt{V_\mathrm{n,rms}^2} = \sqrt{1.38 \cdot 10^{-23} \cdot 300 \cdot 0.84 / 1.4 \cdot 10^{-15}} = 1.58\,\text{mV}\)</span>, which is a sizeable value! We run circuits in this technology at <span class="math inline">\(V_\mathrm{DD}= 1.5\,\mathrm{V}\)</span>, which leaves us with a signal swing of ca. <span class="math inline">\(1.1\,\mathrm{V_{pp}}\)</span>, resulting in a dynamic range in this case of <span class="math inline">\(20 \log (1.58 \cdot 10^{-3} / 0.39) \approx -48\,\text{dB}\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Large BW circuits can integrate noise over a wide bandwidth resulting in considerable rms noise.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please build a simulation testbench in Xschem to simulate the noise performance of the MOSFET diode, and confirm the rms noise value that we just calculated. Look at the rms value and the PSD of the noise, and play around with the integration limits. What is the effect? Can you see the flicker noise in the PSD? How much is its contribution to the rms noise?</p>
<p>If you are getting stuck you can look at this Xschem <a href="./xschem/mosfet_diode_noise.sch">testbench</a>, shown in <a href="#fig-mosfet-diode-noise-tb" class="quarto-xref">Figure&nbsp;16</a>.</p>
<div id="fig-mosfet-diode-noise-tb" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mosfet-diode-noise-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="./xschem/mosfet_diode_noise.png" class="lightbox" data-gallery="quarto-lightbox-gallery-30" title="Figure&nbsp;16: Testbench for MOSFET diode noise analysis."><img src="./xschem/mosfet_diode_noise.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mosfet-diode-noise-tb-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;16: Testbench for MOSFET diode noise analysis.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="conclusion-1" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-1">Conclusion</h3>
<p>In this section we investigated the simple MOSFET-diode circuit. We learned important skills like how to derive a small-signal model, how to calculate important features like noise and open-loop gain for stability analysis. We introduced Middlebrook’s method to have a mechanism to open up loops in simulation (and calculation) without disturbing operating points for change loading conditions.</p>
<p>If you feel that you have not yet mastered these topics or are uncertain in the operation of ngspice, please go back to the beginning of the section and read through the theory and redo the exercises.</p>
</section>
</section>
<section id="sec-current-mirror" class="level2">
<h2 class="anchored" data-anchor-id="sec-current-mirror">Current Mirror</h2>
<p>In this section we will look into a fundamental building block which is often used in integrated circuit design, the <strong>current mirror</strong>. A diagram is shown in <a href="#fig-current-mirror" class="quarto-xref">Figure&nbsp;17</a> with one MOSFET diode converting the incoming bias current into a voltage, and two output MOSFETs working as current sources, which are biased from the diode. By properly selecting all <span class="math inline">\(W\)</span> and <span class="math inline">\(L\)</span> the input current can be scaled, and multiple copies can be created atn once. Shown in the figure are two output currents, but any number of parallel branches can be realized.</p>
<div id="cell-fig-current-mirror" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-current-mirror" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-current-mirror-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-current-mirror-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-31" title="Figure&nbsp;17: A current mirror with two output branches."><img src="index_files/figure-html/fig-current-mirror-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-current-mirror-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17: A current mirror with two output branches.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The output current <span class="math inline">\(I_\mathrm{out1}\)</span> is then given by <span class="math display">\[
I_\mathrm{out1} = I_\mathrm{bias} \frac{W_2}{L_2} \frac{L_1}{W_1}
\]</span> and the output current <span class="math inline">\(I_\mathrm{out2}\)</span> is given by <span class="math display">\[
I_\mathrm{out2} = I_\mathrm{bias} \frac{W_3}{L_3} \frac{L_1}{W_1}.
\]</span></p>
<p>For good matching in layout care has to be taken that the MOSFET widths and lengths are constructed out of <strong>unit elements</strong> of identical size, where an appropiate amount of these single units are then arranged in series or parallel configuration to arrive at the target <span class="math inline">\(W\)</span> and <span class="math inline">\(L\)</span>.</p>
<p>As we know from earlier investigations of the MOSFET performance in <a href="#sec-gmid-method" class="quarto-xref">Section&nbsp;3</a> the drain current of a MOSFET is a function of <span class="math inline">\(V_\mathrm{GS}\)</span> and <span class="math inline">\(V_\mathrm{DS}\)</span>. As long as the MOSFET stays in saturation (i.e., <span class="math inline">\(V_\mathrm{DS}&gt; V_\mathrm{ds,dsat}\)</span>) the drain current is just a mild function of <span class="math inline">\(V_\mathrm{DS}\)</span> (essentially the effect of <span class="math inline">\(g_\mathrm{ds}\)</span>, which is the output conductance of the MOSFET). A fundamental flaw of the basic current mirror shown in <a href="#fig-current-mirror" class="quarto-xref">Figure&nbsp;17</a> is the mismatch of the <span class="math inline">\(V_\mathrm{DS}\)</span> of the MOSFET. The input-side diode has <span class="math inline">\(V_\mathrm{GS}= V_\mathrm{DS}\)</span>, whereas the output current sources have a <span class="math inline">\(V_\mathrm{DS}\)</span> depending on the connected circuitry. Improved current mirrors exist (basically fixing this flaw), still, when just a simple current mirror is required this structure is used for its simplicity.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Exercise">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please construct a current mirror based on the MOSFET-diode which we sized in <a href="#sec-mosfet-diode" class="quarto-xref">Section&nbsp;4</a>. The input current <span class="math inline">\(I_\mathrm{bias} = 20\,\mu\text{A}\)</span>, and we want three output currents of size <span class="math inline">\(10\,\mu\text{A}\)</span>, <span class="math inline">\(20\,\mu\text{A}\)</span>, and <span class="math inline">\(40\,\mu\text{A}\)</span>.</p>
<p>Sweep the output voltage of all three current branches and see over which voltage range an acceptable current is created. For which output voltage range is the current departing from its ideal value, and why?</p>
<p>You see that the slope of the output current is quite bad, as <span class="math inline">\(g_\mathrm{ds}\)</span> is too large. We can improve this by changing the length to <span class="math inline">\(L = 5\,\mu\text{m}\)</span> (for motivation, please look at the graphs in <a href="#sec-gmid-method" class="quarto-xref">Section&nbsp;3</a>). In addition, for a current mirror we are not interested in a high <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}\)</span> value, so we can use <span class="math inline">\(g_\mathrm{m}/I_\mathrm{D}= 5\)</span> in this case. Please size the current mirror MOSFETs accordinly (please round the <span class="math inline">\(W\)</span> to half micron, to keep sizes a bit more practical). Compare this result to the previous one, what changed?</p>
<p>In case you get stuck, here are Xschem schematics for the <a href="./xschem/current_mirror.sch">original</a> and the <a href="./xschem/current_mirror_improved.sch">improved</a> current mirrors.</p>
</div>
</div>
</section>
<section id="sec-diff-pair" class="level2">
<h2 class="anchored" data-anchor-id="sec-diff-pair">Differential Pair</h2>
<p>Like the current mirror in <a href="#sec-current-mirror" class="quarto-xref">Section&nbsp;5</a> the <strong>differential pair</strong> is an ubiquitous building block often used in integrated circuit design. The fundamental structure is given in <a href="#fig-differential-pair" class="quarto-xref">Figure&nbsp;18</a>.</p>
<div id="cell-fig-differential-pair" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div id="fig-differential-pair" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-differential-pair-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-differential-pair-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-32" title="Figure&nbsp;18: A differential pair."><img src="index_files/figure-html/fig-differential-pair-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-differential-pair-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18: A differential pair.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In order to understand its operation it is instructive to separate the input condition into (1) a purely differential voltage, and (2) into a common-mode voltage, and see what the impact on the output currents is.</p>
<section id="differential-operation-of-the-diffpair" class="level3">
<h3 class="anchored" data-anchor-id="differential-operation-of-the-diffpair">Differential Operation of the Diffpair</h3>
<p>For a differential mode of operation we assume that the input common mode voltage is constant, i.e.&nbsp;<span class="math inline">\(V_\mathrm{in,p} + V_\mathrm{in,n} = V_\mathrm{CM}\)</span>. A differential input voltage <span class="math inline">\(v_\mathrm{in}\)</span> then results in <span class="math display">\[
V_\mathrm{in,p} = V_\mathrm{CM} + \frac{v_\mathrm{in}}{2}
\]</span> and <span class="math display">\[
V_\mathrm{in,n} = V_\mathrm{CM} - \frac{v_\mathrm{in}}{2}.
\]</span></p>
<p>For a small-signal differential drive the potential at the tail point stays constant and we can treat it as a virtual ground. The output current on each side is then given by (neglecting <span class="math inline">\(g_\mathrm{ds}\)</span> and <span class="math inline">\(g_\mathrm{mb}\)</span> of <span class="math inline">\(M_1\)</span> and <span class="math inline">\(M_2\)</span>) <span class="math display">\[
i_\mathrm{out,p} = g_\mathrm{m1} \left( \frac{v_\mathrm{in}}{2} \right)
\]</span> and <span class="math display">\[
i_\mathrm{out,n} = g_\mathrm{m2} \left( -\frac{v_\mathrm{in}}{2} \right).
\]</span></p>
<p>Usually we assume symmetry in the differential pair, so <span class="math inline">\(g_\mathrm{m1} = g_\mathrm{m2} = g_\mathrm{m}\)</span>. The differential output current <span class="math inline">\(i_\mathrm{out}\)</span> is then given by <span id="eq-differential-pair-dm"><span class="math display">\[
i_\mathrm{out} = i_\mathrm{out,p} - i_\mathrm{out,n} = g_\mathrm{m}v_\mathrm{in}
\tag{9}\]</span></span></p>
<p>We see in <a href="#eq-differential-pair-dm" class="quarto-xref">Equation&nbsp;9</a> that the differential output current is simply the differential input voltage multiplied by the <span class="math inline">\(g_\mathrm{m}\)</span> of the individual transistor. We also note that the bottom conductance <span class="math inline">\(g_\mathrm{tail}\)</span> plays no role for the small-signal differential operation.</p>
</section>
<section id="common-mode-operation-of-the-diffpair" class="level3">
<h3 class="anchored" data-anchor-id="common-mode-operation-of-the-diffpair">Common-Mode Operation of the Diffpair</h3>
<p>Usually, the source conductance <span class="math inline">\(g_\mathrm{tail}\)</span> is realized by a current source and ideally should be <span class="math inline">\(g_\mathrm{tail} = 0\)</span>. If this is the case, then the output currents are not a function of the common-mode input voltage (at least as long as bias points keep the MOSFET in triode), and (<span class="math inline">\(I_\mathrm{tail}\)</span> is set by the tail current source) <span class="math display">\[
I_\mathrm{out,p} = I_\mathrm{out,n} = \frac{I_\mathrm{tail}}{2}.
\]</span></p>
<p>However, if we assume a realistic tail current source then <span class="math inline">\(g_\mathrm{tail} &gt; 0\)</span>. For analysis we can simply look at a half circuit since everything is symmetric. In order to simplify the analysis a bit we remove all capacitors from the MOSFET small-signal model and set <span class="math inline">\(g_\mathrm{ds}= g_\mathrm{mb}= 0\)</span>. We arrive then at the small-signal equivalent circuit shown in <a href="#fig-differential-pair-cm" class="quarto-xref">Figure&nbsp;19</a> (note that we set <span class="math inline">\(v_\mathrm{in,p} = v_\mathrm{in,n} = v_\mathrm{in}\)</span> and <span class="math inline">\(i_\mathrm{out,p} = i_\mathrm{out,n} = i_\mathrm{out}\)</span> under symmetry considerations).</p>
<div id="cell-fig-differential-pair-cm" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-differential-pair-cm" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-differential-pair-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-differential-pair-cm-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-33" title="Figure&nbsp;19: Small-signal model of the differential pair half-circuit in common-mode operation."><img src="index_files/figure-html/fig-differential-pair-cm-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-differential-pair-cm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;19: Small-signal model of the differential pair half-circuit in common-mode operation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Formulating KVL for the input-side loop we get <span class="math display">\[
v_\mathrm{in} = v_\mathrm{gs}+ \frac{i_\mathrm{ds}}{g_\mathrm{tail}}.
\]</span></p>
<p>With <span class="math inline">\(i_\mathrm{out} = i_\mathrm{ds}= g_\mathrm{m}v_\mathrm{gs}\)</span> we arrive at <span id="eq-differential-pair-cm"><span class="math display">\[
i_\mathrm{out} = \frac{g_\mathrm{m}g_\mathrm{tail}}{g_\mathrm{m}+ g_\mathrm{tail}} v_\mathrm{in}
\tag{10}\]</span></span></p>
<p>Interpreting <a href="#eq-differential-pair-cm" class="quarto-xref">Equation&nbsp;10</a> we can distinguish the following extreme cases:</p>
<ol type="1">
<li>If <span class="math inline">\(g_\mathrm{tail} = 0\)</span> (ideal tail current source) then <span class="math inline">\(i_\mathrm{out} = 0\)</span>, the common-mode voltage variation from the input is suppressed and does not show up at the common-mode output current (which is constant due to the ideal tail current source). This is usually the case that we want to achieve.</li>
<li>If <span class="math inline">\(g_\mathrm{tail} = \infty\)</span> then <span class="math inline">\(i_\mathrm{out} = g_\mathrm{m}v_\mathrm{in}\)</span>, which means the output current is a function of the MOSFET <span class="math inline">\(g_\mathrm{m}\)</span>. If everything is perfectly matched, then the differential output current is zero, but the common-mode output current changes according to the common-mode input voltage. In special cases this can be a wanted behaviour, this configuration is called a “pseudo-differential pair.”</li>
</ol>
</section>
</section>
<section id="sec-basic-ota" class="level2">
<h2 class="anchored" data-anchor-id="sec-basic-ota">A Basic 5-Transistor OTA</h2>
<p>Suited with the knowledge of basic transitor operation (<a href="#sec-first-steps" class="quarto-xref">Section&nbsp;2</a> and <a href="#sec-gmid-method" class="quarto-xref">Section&nbsp;3</a>) and the working knowledge of the current mirror (<a href="#sec-mosfet-diode" class="quarto-xref">Section&nbsp;4</a> and <a href="#sec-current-mirror" class="quarto-xref">Section&nbsp;5</a>) as well as the differential pair (<a href="#sec-diff-pair" class="quarto-xref">Section&nbsp;6</a>) we can now start to design our first real circuit. A fundamental (simple) circuit that is often used for basic tasks is the 5-transistor operational transconductance amplifier (OTA). A circuit diagram of this 5T-OTA is shown in <a href="#fig-basic-ota" class="quarto-xref">Figure&nbsp;20</a>.</p>
<div id="cell-fig-basic-ota" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-basic-ota" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-basic-ota-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-basic-ota-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-34" title="Figure&nbsp;20: The 5-transistor OTA."><img src="index_files/figure-html/fig-basic-ota-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-basic-ota-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20: The 5-transistor OTA.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The operation is as follows: <span class="math inline">\(M_{1,2}\)</span> form a differential pair which is biased by the current source <span class="math inline">\(M_6\)</span>. <span class="math inline">\(M_{5,6}\)</span> form a current mirror, thus the input bias current <span class="math inline">\(I_\mathrm{bias}\)</span> sets the bias current in the OTA. The differential pair <span class="math inline">\(M_{1,2}\)</span> is loaded by the current mirror <span class="math inline">\(M_{3,4}\)</span> which mirrors the output current of <span class="math inline">\(M_1\)</span> to the right side. Here, the currents from <span class="math inline">\(M_4\)</span> and <span class="math inline">\(M_2\)</span> are summed, and together with the conductance effective at the output node a voltage builds up.</p>
<p>As this is an OTA the output is a current; if the load impedance is high (i.e., purely capacitive) then the voltage gain of the OTA can be high (of course, in this simple OTA it is limited). With a high-impedance loading this OTA can provide a voltage output, and this is actually how OTAs are mostly operated.</p>
<section id="voltage-buffer-with-ota" class="level3">
<h3 class="anchored" data-anchor-id="voltage-buffer-with-ota">Voltage Buffer with OTA</h3>
<p>In order to design an OTA we need an application, and from this we need to derive the circuit specifications. We want to use this OTA to realize a voltage buffer which lighly loads a voltage source and can drive a large capacitive load. Such a configuration is often used to, e.g., buffer a reference voltage that is needed (and thus loaded) by another circuit. The block diagram of this configuration is shown in <a href="#fig-voltage-buffer-ota" class="quarto-xref">Figure&nbsp;21</a>.</p>
<div id="cell-fig-voltage-buffer-ota" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div id="fig-voltage-buffer-ota" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-voltage-buffer-ota-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/fig-voltage-buffer-ota-output-1.svg" class="lightbox" data-gallery="quarto-lightbox-gallery-35" title="Figure&nbsp;21: A voltage buffer (based on OTA) driving a capacitive load."><img src="index_files/figure-html/fig-voltage-buffer-ota-output-1.svg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-voltage-buffer-ota-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21: A voltage buffer (based on OTA) driving a capacitive load.
</figcaption>
</figure>
</div>
</div>
</div>
<p>If the voltage gain of the OTA is <a href="#fig-voltage-buffer-ota" class="quarto-xref">Figure&nbsp;21</a> is high, then <span class="math inline">\(V_\mathrm{out} \approx V_\mathrm{in}\)</span>. We now want to design an OTA for this application for the following spefication values (see <a href="#tbl-voltage-buffer-spec" class="quarto-xref">Table&nbsp;1</a>).</p>
<div id="tbl-voltage-buffer-spec" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-voltage-buffer-spec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Voltage buffer specification
</figcaption>
<div aria-describedby="tbl-voltage-buffer-spec-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 54%">
<col style="width: 36%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Specification</th>
<th style="text-align: center;">Value</th>
<th style="text-align: center;">Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Load capacitance <span class="math inline">\(C_\mathrm{load}\)</span></td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">fF</td>
</tr>
<tr class="even">
<td style="text-align: left;">Input voltage range (for buffering bandgap voltage)</td>
<td style="text-align: center;">1.1—1.3</td>
<td style="text-align: center;">V</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Signal bandwidth (3dB)</td>
<td style="text-align: center;">&gt;1</td>
<td style="text-align: center;">MHz</td>
</tr>
<tr class="even">
<td style="text-align: left;">Voltage gain error</td>
<td style="text-align: center;">&lt;1</td>
<td style="text-align: center;">%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total output noise (rms)</td>
<td style="text-align: center;">&lt;1</td>
<td style="text-align: center;">mV<sub>rms</sub></td>
</tr>
<tr class="even">
<td style="text-align: left;">Supply voltage</td>
<td style="text-align: center;">1.45—1.5—1.55</td>
<td style="text-align: center;">V</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Supply current (as low as possible)</td>
<td style="text-align: center;">&lt;100</td>
<td style="text-align: center;">µA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stability</td>
<td style="text-align: center;">stable for rated <span class="math inline">\(C_\mathrm{load}\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Turn-on time (settled to with 1%)</td>
<td style="text-align: center;">&lt;10</td>
<td style="text-align: center;">µs</td>
</tr>
<tr class="even">
<td style="text-align: left;">Externally provided bias current (nominal)</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">µA</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="large-signal-analysis-of-the-ota" class="level3">
<h3 class="anchored" data-anchor-id="large-signal-analysis-of-the-ota">Large-Signal Analysis of the OTA</h3>
<p>The first step when receiving a design task is to look at the specifications, and see whether they make sense. Detailed performance of the design will be the result of the circuit simulation, but before we step into sizing we need to do a few simple calculations to (a) allows to do back-of-the-envelope gauging if the specification makes sense, and (b) the derived analytical equations will serve as guide for the sizing procedure.</p>
<ul>
<li>In terms of large-signal operation, we will now check whether the input and output voltage range, as well as the settling time can be roughly met.</li>
<li>When the input is at its maximum of <span class="math inline">\(1.3\,\text{V}\)</span>, we see that we need to keep <span class="math inline">\(M_1\)</span> in saturation. We can calculate that <span class="math inline">\(V_\mathrm{DS1} = V_\mathrm{DD}- V_\mathrm{GS3} + V_\mathrm{GS1} - V_\mathrm{in} = 1.45 - 0.6 + 0.6 - 1.3 = 0.15\,\text{V}\)</span>, which barely leaves enough margin, so we must keep the gate-source voltages of <span class="math inline">\(M_1\)</span> and <span class="math inline">\(M_3\)</span> resonably small.</li>
<li>When the input is at its minimum of <span class="math inline">\(1.1\,\text{V}\)</span>, we see that the <span class="math inline">\(V_\mathrm{DS}\)</span> of <span class="math inline">\(M_6\)</span> is calculated as <span class="math inline">\(V_\mathrm{DS6} = V_\mathrm{in} - V_\mathrm{GS1} = 1.1 - 0.6 = 0.5\,\text{V}\)</span>, so this leaves plenty of margin.</li>
<li>For the output voltage, when the output voltage is on the high side, it leaves <span class="math inline">\(V_\mathrm{DS4} = V_\mathrm{DD}- V_\mathrm{out} = 1.45 - 1.3 = 0.15\,\text{V}\)</span>, whis is on the edge.</li>
<li>When the output voltage is on the low side, it leaves <span class="math inline">\(V_\mathrm{DS2} = V_\mathrm{out} - V_\mathrm{in} + V_\mathrm{GS2} = 1.3 - 1.55 + 0.6 = 0.35\,\text{V}\)</span>, so this should work.</li>
</ul>
<p>In summary, we think that we can make an NMOS-input OTA like the one in <a href="#fig-basic-ota" class="quarto-xref">Figure&nbsp;20</a> work for the required supply and input- and output voltages. If this would not work out, we need to look for further options, like a PMOS-input OTA, or a NMOS/PMOS-input OTA.</p>
<p>Another large-signal specification item that we can quickly check is the settling time. Under slewing conditions, we complete bias current in the OTA is steered towards the output (try to understand why this is the case), so when the output capacitor is fully discharged, and we assume just a linear ramp due to constant-current charging of the output capacitor, the settling time is <span class="math display">\[
T_\mathrm{slew} \approx \frac{C_\mathrm{load} V_\mathrm{out}}{I_\mathrm{tail}} = \frac{50 \cdot 10^{-15} \cdot 1.3}{100 \cdot 10^{-6}} = 0.65\,\text{ns}
\]</span> so this leaves plenty of margin for additional slow-signal settling due to the limited bandwidth, as well as reducing the supply current.</p>
<p>The small-signal settling (assuming one pole at the bandwidth corner frequency) leads to an approximate settling time (1% error corresponds to <span class="math inline">\(\approx 5 \tau\)</span>) of <span class="math display">\[
T_\mathrm{slew} \approx \frac{5}{2 \pi f_\mathrm{c}} = \frac{5}{2 \pi \cdot 1 \cdot 10^{-6}} = 0.8\,\mu\text{s}.
\]</span> which also checks out.</p>
</section>
<section id="small-signal-analysis-of-the-ota" class="level3">
<h3 class="anchored" data-anchor-id="small-signal-analysis-of-the-ota">Small-Signal Analysis of the OTA</h3>
</section>
</section>
<section id="cascode-stage" class="level2">
<h2 class="anchored" data-anchor-id="cascode-stage">Cascode Stage</h2>
</section>
<section id="a-fully-differential-ota" class="level2">
<h2 class="anchored" data-anchor-id="a-fully-differential-ota">A Fully-Differential OTA</h2>
</section>
<section id="biasing-the-ota" class="level2">
<h2 class="anchored" data-anchor-id="biasing-the-ota">Biasing the OTA</h2>
</section>
<section id="an-rc-opamp-filter" class="level2">
<h2 class="anchored" data-anchor-id="an-rc-opamp-filter">An RC-OPAMP Filter</h2>
</section>
<section id="summary-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="summary-conclusion">Summary &amp; Conclusion</h2>
</section>
<section id="appendix-ngspice-cheat-sheet" class="level2">
<h2 class="anchored" data-anchor-id="appendix-ngspice-cheat-sheet">Appendix: ngspice Cheat Sheet</h2>
</section>
<section id="appendix-xschem-cheat-sheet" class="level2 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Appendix: Xschem Cheat Sheet</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Hellen_2003" class="csl-entry" role="listitem">
Hellen, Edward H. 2003. <span>“<span class="nocase">Verifying the diode–capacitor circuit voltage decay</span>.”</span> <em>American Journal of Physics</em> 71 (8): 797–800. <a href="https://doi.org/10.1119/1.1578070">https://doi.org/10.1119/1.1578070</a>.
</div>
<div id="ref-Chenming_Hu_2010" class="csl-entry" role="listitem">
Hu, Chenming. 2010. <em>Modern Semiconductor Devices for Integrated Circuits</em>. Pearson.
</div>
<div id="ref-Jespers_Murmann_2017" class="csl-entry" role="listitem">
Jespers, Paul G. A., and Boris Murmann. 2017. <em>Systematic Design of Analog CMOS Circuits: Using Pre-Computed Lookup Tables</em>. Cambridge University Press.
</div>
<div id="ref-Middlebrook_1975" class="csl-entry" role="listitem">
Middlebrook, R. D. 1975. <span>“<span class="nocase">Measurement of loop gain in feedback systems</span>.”</span> <em>International Journal of Electronics</em> 38 (4): 485–512. <a href="https://doi.org/10.1080/00207217508920421">https://doi.org/10.1080/00207217508920421</a>.
</div>
<div id="ref-Nagel_1975" class="csl-entry" role="listitem">
Nagel, Laurence W. 1975. <span>“SPICE2: A Computer Program to Simulate Semiconductor Circuits.”</span> PhD thesis, EECS Department, University of California, Berkeley. <a href="http://www2.eecs.berkeley.edu/Pubs/TechRpts/1975/9602.html">http://www2.eecs.berkeley.edu/Pubs/TechRpts/1975/9602.html</a>.
</div>
<div id="ref-Tsividis_McAndrew_2011" class="csl-entry" role="listitem">
Tsividis, Yannis, and Colin McAndrew. 2011. <em>Operation and Modeling of the MOS Transistor</em>. Oxford University Press.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","selector":".lightbox","loop":false,"descPosition":"bottom","openEffect":"zoom"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>