#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Harald Pretl
# Johannes Kepler University, Institute for Integrated Circuits
# SPDX-License-Identifier: Apache-2.0
"""Generate one revealjs slide deck per chapter included in aicd.qmd.

Writes slides_<chapter>.qmd and the overview page slides.qmd into the project
root (chapter code uses root-relative paths). With --check, only verifies that
the committed files are up to date.
"""

import argparse
import json
import re
import sys
from pathlib import Path

INCLUDE_RE = re.compile(r"^\{\{< include (/content/\S+\.qmd) >\}\}\s*$", re.M)
TITLE_RE = re.compile(r"^# (.+?)(?:\s+\{[^}]*\})?\s*$", re.M)
BIB_KEY_RE = re.compile(r"^@\w+\{\s*([^,\s]+)\s*,", re.M)
CITE_RE = re.compile(r"@([A-Za-z][\w:.-]*\w)")
SKIP = {"/content/_abbrv.qmd"}
GENERATED = "<!-- Generated by slides/gen_decks.py from aicd.qmd. Do not edit. -->"

DECK = """---
title: {title}
subtitle: "Analog (Integrated) Circuit Design"
format:
  revealjs:
    theme: [default, slides/slides.scss]
    slide-level: 2
    slide-number: true
    scrollable: true
    chalkboard: true
    html-math-method: mathjax
    footer: "[Lecture notes](aicd.html)"
bibliography: references.bib
filters:
  - at: pre-ast
    path: slides/slides.lua
---

{generated}

{{{{< include /content/_abbrv.qmd >}}}}
{{{{< include {include} >}}}}
{refs}"""

INDEX = """---
title: "Lecture Slides"
---

{generated}

Slide decks for classroom use, generated automatically from the lecture notes.
In a deck, press `S` for the speaker view (with the full lecture text as notes),
`C` for the chalkboard, and `F` for full screen.

{items}"""


def chapter_includes(book_text):
    return [inc for inc in INCLUDE_RE.findall(book_text) if inc not in SKIP]


def deck_name(include):
    stem = Path(include).stem.lstrip("_")
    return stem[len("sec_"):] if stem.startswith("sec_") else stem


def chapter_title(text):
    match = TITLE_RE.search(text)
    if not match:
        raise ValueError("chapter has no level-1 heading")
    return match.group(1)


def bib_keys(bib_text):
    return set(BIB_KEY_RE.findall(bib_text))


def cites_bibliography(text, keys):
    return any(key in keys for key in CITE_RE.findall(text))


def render_deck(title, include, with_refs):
    refs = "\n::: {#refs}\n:::\n" if with_refs else ""
    return DECK.format(title=json.dumps(title, ensure_ascii=False), generated=GENERATED,
                       include=include, refs=refs)


def render_index(decks):
    items = "".join(f"1. [{title}](slides_{name}.html)\n" for name, title in decks)
    return INDEX.format(generated=GENERATED, items=items)


def _with_includes(root, text):
    """Chapter text plus the text of the files it includes (one level)."""
    parts = [text]
    for inc in INCLUDE_RE.findall(text):
        path = root / inc.lstrip("/")
        if path.exists():
            parts.append(path.read_text(encoding="utf-8"))
    return "\n".join(parts)


def expected_files(root):
    keys = bib_keys((root / "references.bib").read_text(encoding="utf-8"))
    files, decks = {}, []
    for include in chapter_includes((root / "aicd.qmd").read_text(encoding="utf-8")):
        text = (root / include.lstrip("/")).read_text(encoding="utf-8")
        name, title = deck_name(include), chapter_title(text)
        with_refs = cites_bibliography(_with_includes(root, text), keys)
        files[f"slides_{name}.qmd"] = render_deck(title, include, with_refs)
        decks.append((name, title))
    files["slides.qmd"] = render_index(decks)
    return files


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = parser.parse_args(argv)

    files = expected_files(args.root)
    stale = [p.name for p in args.root.glob("slides_*.qmd") if p.name not in files]
    changed = [name for name, content in files.items()
               if not (args.root / name).exists()
               or (args.root / name).read_text(encoding="utf-8") != content]

    if args.check:
        for name in changed + stale:
            print(f"out of date: {name}", file=sys.stderr)
        if changed or stale:
            print("run: python3 slides/gen_decks.py", file=sys.stderr)
            return 1
        return 0

    for name in changed:
        (args.root / name).write_text(files[name], encoding="utf-8")
    for name in stale:
        (args.root / name).unlink()
    print(f"{len(files)} files, {len(changed)} written, {len(stale)} removed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
