# Appendix: Miller's Theorem {#sec-miller-theorem}

Using Miller's theorem we can find the equivalent circuit of an impedance connected between two nodes, and we know the transfer function between these nodes. The given situation is shown in @fig-miller-theorem, and the equivalent circuit is shown in @fig-miller-theorem-equivalent.

{{< include figures/_fig_miller_theorem.qmd >}}
{{< include figures/_fig_miller_theorem_equivalent.qmd >}}

Using Miller's theorem [@Sheikholeslami_2015] we can calculate
$$
Z_1 = \frac{Z}{1 - A} = \frac{Z}{1 - V_\mathrm{B} / V_\mathrm{A}} 
$$
and
$$
Z_2 = \frac{Z}{1 - A^{-1}} = \frac{Z}{1 - V_\mathrm{A} / V_\mathrm{B}} 
$$
to arrive at an equivalent circuit, given that $A = V_\mathrm{B} / V_\mathrm{A}$ is the voltage gain between nodes A and B. A derivation of this theorem is relative straightforward considering the current through $Z$ when looking into the impedance from either node A or node B and calculating an equivalent impedance causing the same current.

Note that if $V_\mathrm{A} = V_\mathrm{B}$ then there is no current flow through $Z$, and accordingly the impedances $Z_1 = Z_2 = \infty$.

Miller's theorem can be quite handy when an impedance is strapped between two nodes, and we want to break this connection in a calculation, e.g., considering the effect of $\CGD$ in a MOSFET.
