::: {.content-hidden}
Copyright (C) 2024 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Appendix: Middlebrook's Method {#sec-middlebrook-method}

If we want to do a closed-loop gain analysis (for stability or other investigations), we have the need to break the loop at one point, apply a stimulus, and monitor the response on the other end. By doing this we want to keep the loading (i.e. the impedance) on both ends similar to the original case. To achieve this, we break the loop at one point by inserting (1) an ac voltage source, and (2) attach an ac current source, as shown in @fig-middlebrook-voltage and @fig-middlebrook-current. The derivation of this approach is presented in [@Middlebrook_1975], and has the big advantage that loading is not changed compared to the closed-loop situation, and the bias points are also unchanged.

{{< include ./figures/_fig_middlebrook_voltage.qmd >}}
{{< include ./figures/_fig_middlebrook_current.qmd >}}

For both cases we do an ac analysis, and find the corresponding transfer functions $T_\mathrm{v}$ and $T_\mathrm{i}$ as
$$
T_\mathrm{v} = -\frac{V_\mathrm{r}}{V_\mathrm{f}}
$$
and
$$
T_\mathrm{i} = -\frac{I_\mathrm{r}}{I_\mathrm{f}}.
$$

Then, we can calculate the open-loop transfer function $T(s) = H_\mathrm{ol(s)}$ as
$$
T(s) = \frac{T_\mathrm{v} T_\mathrm{i} - 1}{T_\mathrm{v} + T_\mathrm{i} + 2} = \frac{V_\mathrm{r} I_\mathrm{r} - V_\mathrm{f} I_\mathrm{f}}{2 V_\mathrm{f} I_\mathrm{f} - V_\mathrm{r} I_\mathrm{f} - V_\mathrm{f} I_\mathrm{r}}.
$$

The four ac quantities $V_\mathrm{f}$, $V_\mathrm{r}$, $I_\mathrm{f}$, and $I_\mathrm{r}$ we can readily find by circuit simulation or calculation.

Please note that Middlebrook's method works well for $T \gg 1$, so it will show inaccuracies at the crossover frequency of the open-loop gain at $T(s) \approx 0$. An improved method (slightly more complicated) can be found in [@Tian_2001].
