::: {.content-hidden}
Copyright (C) 2024 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Appendix: Useful Circuit Theorems

## Miller's Theorem {#sec-miller-theorem}

Using Miller's theorem we can find the equivalent circuit of an impedance connected between two nodes, and we know the transfer function between these nodes. The given situation is shown in @fig-miller-theorem, and the equivalent circuit is shown in @fig-miller-theorem-equivalent.

{{< include ./figures/_fig_miller_theorem.qmd >}}
{{< include ./figures/_fig_miller_theorem_equivalent.qmd >}}

Using Miller's theorem [@Sheikholeslami_2015] we can calculate
$$
Z_1 = \frac{Z}{1 - A} = \frac{Z}{1 - V_\mathrm{B} / V_\mathrm{A}} 
$$
and
$$
Z_2 = \frac{Z}{1 - A^{-1}} = \frac{Z}{1 - V_\mathrm{A} / V_\mathrm{B}} 
$$
to arrive at an equivalent circuit, given that $A = V_\mathrm{B} / V_\mathrm{A}$ is the voltage gain between nodes A and B. A derivation of this theorem is relative straightforward considering the current through $Z$ when looking into the impedance from either node A or node B and calculating an equivalent impedance causing the same current.

Note that if $V_\mathrm{A} = V_\mathrm{B}$ then there is no current flow through $Z$, and accordingly the impedances $Z_1 = Z_2 = \infty$.

Miller's theorem can be quite handy when an impedance is strapped between two nodes, and we want to break this connection in a calculation, e.g., considering the effect of $\CGD$ in a MOSFET.

::: {.callout-note title="Miller's Secret"}
Note that Miller's compensation is so much more than just making a big capacitor out of a small one. There are layers upon layers of subtlety, and huge hidden benefits which can be read in [@Mangelsdorf_2025_miller].
:::

## Bode's Noise Theorem {#sec-bode-noise-theorem}

The total integrated noise of any (no matter how complicated) $RLC$ network (interpreted as a one-port) is given by

$$
\overline{V_\mathrm{n}^2} = kT \left( \frac{1}{C_\infty} - \frac{1}{C_0} \right),
$$

where $C_\infty$ is the capacitance looking into the network with all resistors and inductors open-circuited, and $C_0$ is the capacitance looking into the circuit when all inductors and resistors are shorted [@Pavan_2019].

Reference [@Pavan_2019] is an excellent read deriving Bode's noise theorem from different angles.
