::: {.content-hidden}
Copyright (C) 2024 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Summary & Conclusion

By now, you should be familiar with the use of a schematic entry tool (Xschem) and circuit simulator (ngspice). You have learned the basic performance trade-offs, and the large- and small-signal behavior of the MOSFET. You can use the $\gmid$ method to size MOSFET for class-A operation. You can design simple amplifiers based on OTA structures. In summary, you are on a good way to become a good analog or mixed-signal circuit designer!

::: {.callout-important title="Feedback"}
We hope you have enjoyed these lecture notes! If you have feedback, suggestions, additions, or corrections, please send us an e-mail, create a GitHub issue, or provide a GitHub pull request. Thank you in advance for your contributions!
:::

::: {.callout-note title="Further Reading"}
For interested circuit designers, Chapter 5 of [@Dorrer_Master_Thesis] is recommended as a further read. It explains additional circuits, such as the beta-multiplier reference, an OTA with a telescopic input stage, and a push-pull output stage, designs them with the $\gmid$ methodology, and simulates them in Xschem and with CACE. Hence, the design flow is the same as proposed in this course.
:::