::: {.content-hidden}
Copyright (C) 2024-2025 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# Differential Pair {#sec-diff-pair}

Like the current mirror in @sec-current-mirror the **differential pair** is a ubiquitous building block often used in integrated circuit design [@Blumlein_1937]. The fundamental structure is given in @fig-differential-pair.

{{< include /content/diffpair/_fig_differential_pair.qmd >}}

In order to understand its operation it is instructive to separate the input condition into

1. a purely differential voltage, and
2. a common-mode voltage,

and see what the impact on the output currents is.

## Differential Operation of the Diffpair

For a differential mode of operation we assume that the input common mode voltage is constant, i.e., $(V_\mathrm{in,p} + V_\mathrm{in,n})/2 = V_\mathrm{CM}$. The differential input voltage $v_\mathrm{in} = V_\mathrm{in,p} - V_\mathrm{in,n}$, so that
$$
V_\mathrm{in,p} = V_\mathrm{CM} + \frac{v_\mathrm{in}}{2}
$$
and
$$
V_\mathrm{in,n} = V_\mathrm{CM} - \frac{v_\mathrm{in}}{2}.
$$

For a small-signal differential drive the potential at the tail point stays constant and we can treat it as a virtual ground. The output current on each side is then given by (neglecting $\gds$ and $\gmb$ of $M_1$ and $M_2$)
$$
I_\mathrm{out,p} = \gm[1] \left( \frac{V_\mathrm{in}}{2} \right)
$$
and
$$
I_\mathrm{out,n} = \gm[2] \left( -\frac{V_\mathrm{in}}{2} \right).
$$

Usually we assume symmetry in the differential pair, so $\gm[1] = \gm[2] = \gm$. The differential output current $I_\mathrm{out}$ is then given by
$$
I_\mathrm{out} = I_\mathrm{out,p} - I_\mathrm{out,n} = \gm V_\mathrm{in}
$$ {#eq-differential-pair-dm}

We see in @eq-differential-pair-dm that the differential output current is simply the differential input voltage multiplied by the $\gm$ of the individual transistor. We also note that the bottom conductance $g_\mathrm{tail}$ plays no role for the small-signal differential operation.

## Common-Mode Operation of the Diffpair

Usually, the source conductance $g_\mathrm{tail}$ is realized by a current source and ideally should be $g_\mathrm{tail} = 0$. If this is the case, then the output currents are not a function of the common-mode input voltage ($I_\mathrm{tail}$ is set by the tail current source), and
$$
I_\mathrm{out,p} = I_\mathrm{out,n} = \frac{I_\mathrm{tail}}{2}.
$$

However, if we assume a realistic tail current source then $g_\mathrm{tail} > 0$. For analysis we can simply look at a half circuit since the circuit operation is symmetric. In order to simplify the analysis a bit we remove all capacitors from the MOSFET small-signal model and set $\gds = \gmb = 0$. We then arrive at the small-signal equivalent circuit shown in @fig-differential-pair-cm (note that we set $V_\mathrm{in,p} = V_\mathrm{in,n} = V_\mathrm{in}$ and $I_\mathrm{out,p} = I_\mathrm{out,n} = I_\mathrm{out}$ under symmetry considerations).

{{< include /content/diffpair/_fig_differential_pair_cm.qmd >}}

Formulating KVL for the input-side loop we get
$$
V_\mathrm{in} = \Vgs + \frac{\Id}{g_\mathrm{tail}}.
$$

With $I_\mathrm{out} = \Id = \gm \Vgs$ we arrive at
$$
I_\mathrm{out} = \frac{\gm g_\mathrm{tail}}{\gm + g_\mathrm{tail}} V_\mathrm{in}
$$ {#eq-differential-pair-cm}

Interpreting @eq-differential-pair-cm we can distinguish the following extreme cases:

1. If $g_\mathrm{tail} = 0$ (ideal tail current source) then $I_\mathrm{out} = 0$, the common-mode voltage variation from the input is suppressed and does not show up at the common-mode output current (which is constant due to the ideal tail current source). This is usually the case that we want to achieve.
2. If $g_\mathrm{tail} \rightarrow \infty$ then $I_\mathrm{out} = \gm V_\mathrm{in}$, which means the output current is a function of the MOSFET $\gm$. If everything is perfectly matched, then the differential output current is zero, but the common-mode output current changes according to the common-mode input voltage. In special cases this can be a wanted behavior, this configuration is called a "pseudo-differential pair."
3. For the typical case that $\gm \gg g_\mathrm{tail}$ then $I_\mathrm{out} \approx g_\mathrm{tail} V_\mathrm{in}$.

Note that the result of @eq-differential-pair-cm is also valid for the general case of a degenerated common-source transistor stage (see @fig-common-source-degenerated). The effective transconductange $\gm'$ is given by ($R_\mathrm{degen} = g_\mathrm{tail}^{-1}$)

$$
\gm' = \frac{I_\mathrm{out}}{V_\mathrm{in}} = \frac{\gm g_\mathrm{tail}}{\gm + g_\mathrm{tail}} = \frac{1}{\gm^{-1} + R_\mathrm{degen}}.
$$

When no degeneration resistor is used, then $\gm' = \gm$. If a degeneration of $R_\mathrm{degen} \gg \gm^{-1}$ is used then $\gm' = 1 / R_\mathrm{degen}$. This result is worth memorizing.

{{< include /content/diffpair/_fig_common_source_degenerated.qmd >}}
