#!/usr/bin/env python3
# -------------------------------------------------
# Generate one reveal.js deck per chapter of aicd.qmd
# -------------------------------------------------
# SPDX-FileCopyrightText: 2026 Harald Pretl
# Johannes Kepler University, Institute for Integrated Circuits
# SPDX-License-Identifier: Apache-2.0
#
# Writes (relative to the project root):
#   slides/<topic>.qmd             one deck per chapter and appendix
#   slides/index.qmd               overview page linking all decks
#   slides/_tools/numbers.json     book numbering of every sec/fig/eq/tbl/nte/imp label
#
# Usage:
#   python3 slides/_tools/gen_decks.py           # (re)generate files
#   python3 slides/_tools/gen_decks.py --check   # exit 1 if generated files are stale

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BOOK = "aicd.qmd"
EXCLUDE_TOPICS = {"exam_questions"}  # chapters without a deck
MARKER = "# Generated by slides/_tools/gen_decks.py from " + BOOK + " -- do not edit."

RE_INCLUDE = re.compile(r"^\{\{<\s*include\s+/?(\S+?)\s*>\}\}\s*$")
RE_EMBED = re.compile(r"\{\{<\s*embed\s+/?(\S+?)#((?:fig|tbl)-[\w-]+)\s*>\}\}")
# chapters: content/<topic>/_sec_*.qmd; appendices: content/<dir>/_app_<topic>.qmd
RE_CHAPTER_FILE = re.compile(r"^content/(\w+)/_(sec|app)_(\w+)\.qmd$")
RE_FENCE = re.compile(r"^(`{3,}|~{3,})")
RE_DIV_OPEN = re.compile(r"^(:{3,})\s*\S")
RE_DIV_CLOSE = re.compile(r"^(:{3,})\s*$")
RE_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
RE_ATTR = re.compile(r"\{([^{}]*)\}\s*$")
RE_CELL_LABEL = re.compile(r"^#\|\s*label:\s*((?:fig|tbl)-[\w-]+)")
# attribute block with the label anywhere in it, but not a {{< shortcode >}}
RE_LABEL_ATTR = re.compile(r"\{(?![{<])[^{}]*?#((?:fig|eq|tbl|nte|imp)-[\w-]+)")
RE_BIB_KEY = re.compile(r"^@\w+\{\s*([^,\s]+)\s*,", re.M)
RE_CITE = re.compile(r"@([A-Za-z][\w:.-]*\w)")

PREFIX = {"sec": "Section", "fig": "Figure", "eq": "Equation",
          "tbl": "Table", "nte": "Note", "imp": "Important"}


def expand(path, root=ROOT):
    """Lines of a qmd file with nested includes expanded, in document order."""
    for line in (root / path).read_text(encoding="utf-8").splitlines():
        m = RE_INCLUDE.match(line.strip())
        if m:
            yield from expand(m.group(1), root)
        else:
            yield line


def book_lines(root=ROOT):
    """(line, top-level include) of the whole book, front matter skipped.

    Headings written directly in the book (not in an included file) count as
    chapters, too; their include is None.
    """
    lines = (root / BOOK).read_text(encoding="utf-8").splitlines()
    start = 0
    if lines and lines[0].strip() == "---":
        start = next(i for i in range(1, len(lines)) if lines[i].strip() == "---") + 1
    for line in lines[start:]:
        m = RE_INCLUDE.match(line.strip())
        if m:
            for sub in expand(m.group(1), root):
                yield sub, m.group(1)
        else:
            yield line, None


def embed_is_numbered(notebook, label, root=ROOT):
    """True if Quarto numbers the embedded notebook cell `label`.

    Only a label in the cell's leading `#|` option block makes the output a
    numbered figure/table; otherwise Quarto finds the cell by tag and embeds
    it unnumbered. Missing notebooks are assumed to be numbered.
    """
    path = root / notebook
    if not path.exists():
        return True
    for cell in json.loads(path.read_text(encoding="utf-8")).get("cells", []):
        source = cell.get("source", "")
        lines = (source if isinstance(source, str) else "".join(source)).splitlines()
        options = []
        for line in lines:
            if not line.startswith("#|"):
                break
            options.append(line)
        if any(RE_CELL_LABEL.match(o) and RE_CELL_LABEL.match(o).group(1) == label
               for o in options):
            return True
    return False


def _div_hidden_in_book(opener):
    """True if a div opener hides its content from the HTML book."""
    fmt = re.search(r'when-format="([^"]+)"', opener)
    if "content-hidden" in opener:
        return fmt is None or fmt.group(1) in ("html", "html5")
    if "content-visible" in opener:
        return fmt is not None and fmt.group(1) == "revealjs"
    return False


def walk_book(root=ROOT):
    """Replicate Quarto's HTML numbering for the whole book.

    Returns (labels, chapters): labels is {label: {"type", "number",
    "chapter"}} where chapter is the number of the level-1 heading the label
    belongs to; chapters is a list of {"include", "number", "title", "sec_id"}
    for every numbered level-1 heading.
    """
    labels = {}
    chapter_list = []
    counters = {"fig": 0, "eq": 0, "tbl": 0, "nte": 0, "imp": 0}
    sec = [0] * 6
    chapter = 0
    fence = None      # opening fence string while inside a code block
    divs = []         # stack of (colons, is_callout, hidden)

    def add(label, kind):
        if kind == "sec":
            return
        counters[kind] += 1
        labels[label] = {"type": kind, "number": str(counters[kind]),
                         "chapter": chapter}

    for line, include in book_lines(root):
        hidden = any(d[2] for d in divs)
        if fence:
            if line.strip().startswith(fence):
                fence = None
            elif not hidden:
                m = RE_CELL_LABEL.match(line.strip())
                if m:
                    add(m.group(1), m.group(1).split("-")[0])
            continue
        m = RE_FENCE.match(line.strip())
        if m:
            fence = m.group(1)
            continue
        m = RE_DIV_CLOSE.match(line)
        if m and divs:
            divs.pop()
            continue
        m = RE_DIV_OPEN.match(line)
        if m:
            divs.append((m.group(1), "callout" in line,
                         _div_hidden_in_book(line)))
            if not hidden and not _div_hidden_in_book(line):
                lab = RE_LABEL_ATTR.search(line)
                if lab:
                    add(lab.group(1), lab.group(1).split("-")[0])
            continue
        if hidden:
            continue
        h = RE_HEADING.match(line)
        if h and not any(d[1] for d in divs):
            attr = RE_ATTR.search(h.group(2))
            attrs = attr.group(1) if attr else ""
            if "unnumbered" in attrs or re.search(r"(^|\s)-(\s|$)", attrs):
                continue
            level = len(h.group(1))
            sec[level - 1] += 1
            sec[level:] = [0] * (6 - level)
            ident = re.search(r"#(sec-[\w-]+)", attrs)
            if level == 1:
                chapter = sec[0]
                chapter_list.append({
                    "include": include, "number": chapter,
                    "title": RE_ATTR.sub("", h.group(2)).strip(),
                    "sec_id": ident.group(1) if ident else ""})
            if ident:
                labels[ident.group(1)] = {
                    "type": "sec",
                    "number": ".".join(str(n) for n in sec[:level]),
                    "chapter": chapter}
            continue
        for lab in RE_LABEL_ATTR.findall(line):
            add(lab, lab.split("-")[0])
        for notebook, lab in RE_EMBED.findall(line):
            if embed_is_numbered(notebook, lab, root):
                add(lab, lab.split("-")[0])
    return labels, chapter_list


def number_labels(root=ROOT):
    return walk_book(root)[0]


def chapters(root=ROOT):
    """Deck records for chapters that come from a _sec_ or _app_ file."""
    out = []
    seen = set()
    for ch in walk_book(root)[1]:
        m = RE_CHAPTER_FILE.match(ch["include"] or "")
        if not m or ch["include"] in seen:
            continue
        seen.add(ch["include"])
        topic = m.group(1) if m.group(2) == "sec" else m.group(3)
        out.append(dict(ch, topic=topic, file=ch["include"], deck=f"{topic}.qmd"))
    return out


def cites_bibliography(path, keys, root=ROOT):
    """True if the chapter (with its includes) cites a bibliography entry."""
    return any(key in keys for line in expand(path, root)
               for key in RE_CITE.findall(line))


DECK_TEMPLATE = """\
---
{marker}
title: {title}
subtitle: "Analog (Integrated) Circuit Design"
aicd-chapter: {number}
number-offset: [{offset}]
execute:
  freeze: false
format:
  revealjs:
    slide-level: 3
    width: 1280
    height: 720
    number-sections: true
    slide-number: c/t
    scrollable: true
    chalkboard: true
    theme: [default, _tools/slides.scss]
    footer: "[AICD lecture notes](../aicd.html{anchor})"
    menu:
      numbers: true
filters:
  - at: pre-ast
    path: _tools/structure.lua
  - at: post-render
    path: _tools/numbers.lua
bibliography: ../references.bib
---

{{{{< include /content/_abbrv.qmd >}}}}
{{{{< include /{file} >}}}}
{refs}"""

REFS = """
### References {.unnumbered .smaller .scrollable}

::: {#refs}
:::
"""

OVERVIEW_TEMPLATE = """\
---
{marker}
title: "Lecture Slides"
---

Slide decks generated from the [lecture notes](../aicd.html), one per chapter.
Press `S` for speaker notes, `C` for the chalkboard, and `?` for all shortcuts.

{items}"""


def render_files(root=ROOT):
    """Return {relative path: content} of every generated file."""
    labels, _ = walk_book(root)
    bib = root / "references.bib"
    keys = set(RE_BIB_KEY.findall(bib.read_text(encoding="utf-8"))) if bib.exists() else set()
    chs = [ch for ch in chapters(root) if ch["topic"] not in EXCLUDE_TOPICS]
    files = {}
    for ch in chs:
        files["slides/" + ch["deck"]] = DECK_TEMPLATE.format(
            marker=MARKER, title=json.dumps(ch["title"], ensure_ascii=False),
            number=ch["number"], offset=ch["number"] - 1, file=ch["file"],
            anchor="#" + ch["sec_id"] if ch["sec_id"] else "",
            refs=REFS if cites_bibliography(ch["file"], keys, root) else "")
    # Markdown renumbers ordered lists, so start a new list after a gap
    # (a chapter without deck); a new list keeps its first number
    items = ""
    for i, ch in enumerate(chs):
        if i and ch["number"] != chs[i - 1]["number"] + 1:
            items += "\n<!-- -->\n\n"
        items += f"{ch['number']}. [{ch['title']}]({ch['deck'].replace('.qmd', '.html')})\n"
    files["slides/index.qmd"] = OVERVIEW_TEMPLATE.format(marker=MARKER, items=items)
    # decks live in slides/, so links to the book go one level up
    numbers = {"book": "../" + BOOK.replace(".qmd", ".html"), "prefix": PREFIX,
               "labels": labels}
    files["slides/_tools/numbers.json"] = json.dumps(numbers, indent=1,
                                                     sort_keys=True) + "\n"
    return files


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if generated files differ from disk")
    args = ap.parse_args(argv)
    files = render_files(ROOT)
    # decks of removed chapters: generated files that are no longer produced
    removed = [str(p.relative_to(ROOT)) for p in (ROOT / "slides").glob("*.qmd")
               if str(p.relative_to(ROOT)) not in files
               and MARKER in p.read_text(encoding="utf-8")]
    stale = []
    for rel, content in files.items():
        target = ROOT / rel
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(rel)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            print(f"wrote {rel}")
    for rel in removed:
        if args.check:
            stale.append(rel)
        else:
            (ROOT / rel).unlink()
            print(f"removed {rel}")
    if stale:
        print("stale generated files (run python3 slides/_tools/gen_decks.py):",
              *stale, sep="\n  ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
