::: {.content-hidden}
Copyright (C) 2024-2025 Harald Pretl and co-authors (harald.pretl@jku.at)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
:::

# A Basic 5-Transistor OTA {#sec-basic-ota}

Suited with the insights of basic transistor operation (@sec-first-steps and @sec-gmid-method) and the working knowledge of the current mirror (@sec-mosfet-diode and @sec-current-mirror) as well as the differential pair (@sec-diff-pair) we can now start to design our first real circuit. A fundamental (simple) circuit that is often used for basic tasks is the 5-transistor operational transconductance amplifier (OTA). A circuit diagram of this 5T-OTA is shown in @fig-basic-ota.

{{< include /content/ota_basic/_fig_basic_ota.qmd >}}

::: {.callout-warning title="Refresh MOSFET Basic Circuits"}
While we repeat the basics of elementary MOSFET amplifier stages (like common-source stage, common-gate stage, and current mirror) in this course material, the following compendium [@Murmann_MOS_stages_2013] is recommended for review. It is freely available at <https://github.com/bmurmann/Book-on-MOS-stages>.

In addition, we can highly recommend these references [@Gray_Meyer_5th_ed, @Razavi_Analog_CMOS] for further study.
:::

The operation is as follows: $M_{1,2}$ form a differential pair which is biased by the current source $M_5$. $M_{5,6}$ form a current mirror, thus the input bias current $I_\mathrm{bias}$ sets the bias current in the OTA. The differential pair $M_{1,2}$ is loaded by the current mirror $M_{3,4}$ which mirrors the drain current of $M_1$ to the right side. Here, the currents from $M_4$ and $M_2$ are summed, and together with the conductance effective at the output node a voltage builds up.

::: {.callout-note title="Operational Amplifier (op-amp, OPA) vs. Operational Transconductance Amplifier (OTA)"}
An [operational amplifier](https://en.wikipedia.org/wiki/Operational_amplifier) is a universal electronic building block characterized by (in the ideal case):

* infinite input impedance at the input ports ($R_\mathrm{in} \rightarrow \infty$)
* zero output resistance, i.e., a voltage output ($R_\mathrm{out} = 0$)
* infinite voltage gain ($A_\mathrm{v} = V_\mathrm{out} / V_\mathrm{in} \rightarrow \infty$)

An [operational transconductance amplifier](https://en.wikipedia.org/wiki/Operational_transconductance_amplifier) is a building block characterized by (again in the ideal case):

* infinite input impedance at the input ports ($R_\mathrm{in} \rightarrow \infty$)
* infinite output resistance, i.e., a current output ($R_\mathrm{out} \rightarrow \infty$)
* infinite transconductance ($G = I_\mathrm{out} / V_\mathrm{in} \rightarrow \infty$)

In integrated circuits, we very often load an OPA/OTA high-ohmic, i.e., with a capacitive load. Hence, an OTA can be used to create a voltage-mode amplifier with high gain, approaching the properties of the OPA. If an OTA is used to drive a low-ohmic load, the voltage gain will be low, and we have to use this block as a transconductance amplifier. Since the output changes behavior depending on high- or low-ohmic loading, we label the output in @fig-basic-ota accordingly.

Why then implement an OTA instead of an OPA? Usually, an OTA is a simpler structure than an OPA. As a general rule, the simplest circuit that can do a job is usually the best choice.
:::

We note that $M_{1,2}$ and $M_{3,4}$ need to be symmetric, thus will have the same $W$ and $L$ dimensioning. $M_{5,6}$ we scale accordingly to set the correct bias current in the OTA.

## Voltage Buffer with OTA {#sec-voltage-buffer-with-ota}

In order to design an OTA we need an application, and from this we need to derive the circuit specifications. We want to use this OTA to realize a voltage buffer which lightly loads an input voltage source and can drive a large capacitive load. Such a configuration is often used to, e.g., buffer a reference voltage that is needed (and thus loaded) by another circuit. The block diagram of this configuration is shown in @fig-voltage-buffer-ota.

{{< include /content/ota_basic/_fig_voltage_buffer_ota.qmd >}}

If the voltage gain of the OTA in @fig-voltage-buffer-ota is high, then $V_\mathrm{out} \approx V_\mathrm{in}$. We now want to design an OTA for this application fitting the following specification values (see @tbl-voltage-buffer-spec). These values are rather typical of what could be expected for such a buffer design.

| Specification                                           | Value                              | Unit    |
|:--------------------------------------------------------|:----------------------------------:|:-------:|
| Supply voltage                                          | $1.45 < \underline{1.5} < 1.55$    | V       |
| Temperature range (industrial)                          | $-40 < \underline{27} < 125$       | degC    |
| Load capacitance $C_\mathrm{load}$                      | $50$                               | fF      |
| Input voltage range (for buffering 2/3 bandgap voltage) | $0.7 < \underline{0.8} < 0.9$      | V       |
| Signal bandwidth (3dB)                                  | $>10$                              | MHz     |
| Output voltage error                                    | $<3$                               | %       |
| Total output noise (rms)                                | $<1$                               | mV~rms~ |
| Supply current (as low as possible)                     | $<10$                              | µA      |
| Stability                                               | stable for rated $C_\mathrm{load}$ |         |
| Turn-on time (settled to with 1%)                       | $<10$                              | µs      |
| Externally provided bias current (nominal)              | $20$                               | µA      |

: Voltage buffer specification {#tbl-voltage-buffer-spec}

## Large-Signal Analysis of the OTA {#sec-basic-ota-large-signal}

The first step when receiving a design task is to look at the specifications, and see whether they make sense. The detailed performance of the design will be the result of the circuit simulation, but before we step into sizing we need to do a few simple calculations to (a) do back-of-the-envelope gauging if the specification makes sense, and (b) use the derived analytical equations as guide for the sizing procedure.

In terms of large-signal operation, we will now check whether the input and output voltage range, as well as the settling time can be roughly met. Since we do not know yet the resulting $\VGS$ of the transistors we use $0.6\,\text{V}$ as an initial guess. If we run into issues with that guess we know how to later steer the sizing procedure. The follower configuration showing the transistor-level details including estimated operating points is shown in @fig-basic-ota-dcop.

{{< include /content/ota_basic/_fig_basic_ota_dcop.qmd >}}

* When the input is at its maximum of $0.9\,\text{V}$, we see that we need to keep $M_1$ in saturation. We can calculate that $\VDS[1] = \VDD - |\VGS[3]| + \VGS[1] - V_\mathrm{in} = 1.45 - 0.6 + 0.6 - 0.9 = 0.55\,\text{V}$, which leaves enough margin.
* When the input is at its minimum of $0.7\,\text{V}$, we see that the $\VDS[5]$ of $M_5$ is calculated as $\VDS[5] = V_\mathrm{in} - \VGS[1] = 0.7 - 0.6 = 0.1\,\text{V}$, so this leaves little margin, but we can make $\VGS[1]$ smaller, so it should work out.
* For the output voltage, when the output voltage is on the high side, it leaves $|\VDS[4]| = \VDD - V_\mathrm{out} = 1.45 - 0.9 = 0.55\,\text{V}$, which is enough margin.

In summary, we think that we can make an NMOS-input OTA like the one in @fig-basic-ota (and in @fig-basic-ota-dcop) work for the required supply and input- and output-voltages. If this would not work out, we need to look for further options, like a PMOS-input OTA, or a NMOS/PMOS-input OTA.

Another large-signal specification item that we can quickly check is the settling time. Under slewing conditions, the complete bias current in the OTA is steered towards the output (try to understand why this is the case), so when the output capacitor is fully discharged, and we assume just a linear ramp due to constant-current charging of the output capacitor, the settling time is
$$
T_\mathrm{slew} \approx \frac{C_\mathrm{load} V_\mathrm{out}}{I_\mathrm{tail}} = \frac{50 \cdot 10^{-15} \cdot 1.3}{10 \cdot 10^{-6}} = 6.5\,\text{ns}
$$
so this leaves plenty of margin for additional slow-signal settling due to the limited bandwidth, as well as reducing the supply current.

The small-signal settling (assuming one pole at the bandwidth corner frequency) leads to an approximate settling time (1% error corresponds to $\approx 5 \tau$) of
$$
T_\mathrm{settle} \approx \frac{5}{2 \pi f_\mathrm{c}} = \frac{5}{2 \pi \cdot 1 \cdot 10^{6}} = 0.8\,\mu\text{s}.
$$
which also checks out.

## Small-Signal Analysis of the OTA {#sec-basic-ota-small-signal}

In order to size the OTA components we need to derive how the MOSFET parameters define the performance. The important small-signal metrics are

- dc voltage gain $A_0$
- gain-bandwidth product (GBW)
- output noise

The specification for GBW is directly given in @tbl-voltage-buffer-spec, while the dc gain we have to calculate from the voltage accuracy specification. For a voltage follower in the configuration shown in @fig-voltage-buffer-ota the voltage gain is given by
$$
\frac{V_\mathrm{out}}{V_\mathrm{in}} = \frac{A_0}{1 + A_0}.
$$ {#eq-voltage-buffer-tolerance}

So in order to reach an output voltage accuracy of at least 3% we need a dc gain of $A_0 > 30.2\,\text{dB}$. To allow for process and temperature variation we need to add a bit of extra gain as margin. 

::: {.callout-important title="Small-Signal vs. Large-Signal Operation"}
In order to get the correct dc voltage per the specification we require the large-signal gain calculated with @eq-voltage-buffer-tolerance. However, calculating the large-signal gain of a circuit is quite involved (usually mandating the use of a large-signal nonlinear model for the used components), so we typically resort to do a simpler small-signal calculation instead, like in @sec-basic-ota-small-signal. We deliberately introduce this error, but we should not get confused about the difference between large- and small-signal operation!
:::

### OTA Small-Signal Transfer Function

In order to derive the governing small-signal equations for the OTA we will make a few simplifications:

- We will set $\gmb = 0$ for all MOSFETs.
- We will further set $\Cgd = 0$ for all MOSFETs except for $M_4$ where we expect a Miller effect on this capacitor, and we could add its effect by increasing the capacitance at the gate node of $M_{3,4}$ (for background please see @sec-miller-theorem). However, as this does not create a dominant pole in this circuit, we consider this a minor effect (see @eq-simple-ota-gain). Thus, only $\Cgs[34] = \Cgs[3] + \Cgs[4]$ is considered at the gate node of the current mirror load.
- We assume $\gm \gg \gds$, so we set $\gds[1] = \gds[3] = 0$.
- The drain capacitance of $M_2$ and $M_4$, as well as the gate capacitance of $M_2$, we could add to the load capacitance $C_\mathrm{load}$ (see @fig-basic-ota-dcop). Note that adding $\Cgs[2]$ to $C_\mathrm{load}$ is a simplified (in fact erroneous) view, as the tail point (the source connection of $M_1$ and $M_2$) is not an ac ground, but we ignore this for simplicity and accept the error we make due to this, as in our case $C_\mathrm{load}$ is so large that it will dominate anyway.

The resulting small-signal equivalent circuit is shown in @fig-basic-ota-small-signal.

::: {.callout-warning title="Refresh MOSFET Small-Signal Model"}
Please review the MOSFET small-signal equivalent model in @fig-mosfet-small-signal-model at this point. For the PMOS just flip the model upside-down.
:::

{{< include /content/ota_basic/_fig_basic_ota_small_signal.qmd >}}

We can further simplify the output side by recognizing that the impedance (when looking from the output down) is $\gds[2]$ in series with $\gds[5] + \gm[12]$. This is a valid simplification as we treat $M_1$ as a common-gate stage when looking from the output, and since it is loaded by a low impedance of $\gm[34]^{-1}$, we can approximate the impedance looking into the source of $M_1$ with $\gm[12]^{-1}$. With the approximation that $\gm \gg \gds$ the parallel connection of $\gm[12]$ and $\gds[5]$ is dominated by $\gm[12]$ ($\gm[12] + \gds[5] \approx \gm[12]$) and its series connection with $\gds[2]$ ($\gm[12]^{-1} + \gds[2]^{-1} \approx \gds[2]^{-1}$), resulting in the fact that we can ground the lower end of $\gds[2]$. You should probably stop here and read this paragraph again, slowly.

Therefore, we can move $\gds[2] + \gds[4]$ in parallel to $C_\mathrm{load}$. Further, assuming a differential drive with a virtual ground at the tailpoint we can remove $\gds[5]$. The current source $\gm[34] \Vgs[34]$ is replaced with the equivalent conductance $\gm[34]$. All the previous steps result in the further simplified equivalent circuit shown in @fig-basic-ota-small-signal-simplified.

{{< include /content/ota_basic/_fig_basic_ota_small_signal_simplified.qmd >}}

In the simplified circuit model in @fig-basic-ota-small-signal-simplified we can see that we have two poles in the circuit, one at the gate note of $M_{3,4}$, and one at the output. Realizing that $V_\mathrm{in,p} = V_\mathrm{in}/2$ and $V_\mathrm{in,n} = - V_\mathrm{in}/2$ we can formulate KCL at the output node to
$$
-\gm[34] \Vgs[34] - \left( -\gm[12] \frac{V_\mathrm{in}}{2} \right) - V_\mathrm{out} (\gds[2] + \gds[4] + s C_\mathrm{load}) = 0.
$$ {#eq-simple-ota-eq1}
 We further realize that
 $$
\Vgs[34] = -\gm[12] \frac{V_\mathrm{in}}{2} \frac{1}{\gm[34] + s \Cgs[34]}.
 $$ {#eq-simple-ota-eq2}

By combining @eq-simple-ota-eq1 and @eq-simple-ota-eq2 and after a bit of algebraic manipulation we arrive at
$$
A(s) = \frac{V_\mathrm{out}(s)}{V_\mathrm{in}(s)} = \frac{\gm[12]}{2} \frac{2 \gm[34] + s \Cgs[34]}{(\gm[34] + s \Cgs[34]) (\gds[2] + \gds[4] + s C_\mathrm{load})}.
$$ {#eq-simple-ota-gain}

When we now inspect @eq-simple-ota-gain we can see that for low frequencies the (open-loop) gain is
$$
A(s \rightarrow 0) = A_0 = \frac{\gm[12]}{\gds[2] + \gds[4]}
$$ {#eq-simple-ota-gain-dc}
which is plausible, and confirms the requirement of a high impedance at the output node. For very large frequencies we get
$$
A (s \gg) = \frac{\gm[12]}{2 s C_\mathrm{load}}
$$ {#eq-simple-ota-highf}
which is essentially the behavior of an integrator, and we can use @eq-simple-ota-highf to calculate the frequency where the gain drops to $|A(s_\mathrm{ug})| = 1 = \gm[12]/|2 j \omega_\mathrm{ug} C_\mathrm{load}|$:
$$
f_\mathrm{ug} = \frac{\gm[12]}{4 \pi C_\mathrm{load}}
$$

When looking at @eq-simple-ota-gain we see that we have a dominant pole at $s_\mathrm{p}$ and a pole-zero doublet with $s_\mathrm{pd}$/$s_\mathrm{zd}$:
$$
s_\mathrm{p} = -\frac{\gds[2] + \gds[4]}{C_\mathrm{load}}
$$ {#eq-basic-ota-dominant-pole}
$$
s_\mathrm{pd} = -\frac{\gm[34]}{\Cgs[34]}
$$ {#eq-basic-ota-doublet-pole}
$$
s_\mathrm{zd} = -\frac{2 \gm[34]}{\Cgs[34]}
$$ {#eq-basic-ota-doublet-zero}

::: {.callout-note title="Why a Pole-Zero Doublet?"}
Looking at @eq-basic-ota-doublet-pole and @eq-basic-ota-doublet-zero we see that this pair is intimately linked by the same parameters and can only move together. Hence we call it a "doublet". The effects of pole-zero doublets on the frequency response and settling time of OTAs can be found in [@Kamath_1974]. This paper shows that doublets
may cause severe degradation of settling time while only causing minor changes in the frequency response of the amplifier.
:::

### OTA Noise

For the noise analysis we ignore the pole-zero doublet due to $\Cgs[34]$ (we assume minor impact due to this) and just consider the dominant pole given by @eq-basic-ota-dominant-pole. For the noise analysis at the output we set the input signal to zero, and thus we arrive at the simplified small-signal circuit shown in @fig-basic-ota-small-signal-noise.

{{< include /content/ota_basic/_fig_basic_ota_small_signal_noise.qmd >}}

We see that
$$
\overline{\Vgs[34]^2} = \frac{1}{\gm[34]^2} \left( \overline{I_\mathrm{n1}^2} + \overline{I_\mathrm{n3}^2} \right).
$$

::: {.callout-important title="Noise Addition"}
Remember that **uncorrelated** noise quantities need to be power-summed (i.e., $I^2 = I_1^2 + I_2^2$)!
:::

We can then sum the output noise current $\overline{I_\mathrm{n}}$ as
$$
\overline{I_\mathrm{n}^2} = \overline{I_\mathrm{n2}^2} + \overline{I_\mathrm{n4}^2} + \gm[34]^2 \frac{1}{\gm[34]^2} \left( \overline{I_\mathrm{n1}^2} + \overline{I_\mathrm{n3}^2} \right) = 2 \left( \overline{I_\mathrm{n1,2}^2} + \overline{I_\mathrm{n3,4}^2} \right).
$$

As a next step, let us rewrite the OTA transfer function $A(s)$ (see @eq-simple-ota-gain) by getting rid of the pole-zero doublet as a simplifying assumption to get
$$
A'(s) = \frac{\gm[12]}{\gds[2] + \gds[4] + s C_\mathrm{load}}.
$$ {#eq-simple-ota-gain-simplified}

Inspecting @eq-simple-ota-gain-simplified we can interpret the OTA transfer function as a transconductor $\gm[12]$ driving a load of $Y_\mathrm{load} = \gds[2] + \gds[4] + s C_\mathrm{load}$. We can thus redraw @fig-voltage-buffer-ota in the following way, injecting the previously calculated noise current into the output node. The result is shown in @fig-voltage-buffer-ota-noise.

::: {.callout-note title="Output Impedance of the Voltage Buffer"}
For the following analysis it is helpful to calculate the output impedance of the voltage buffer configuration shown in @fig-voltage-buffer-ota-noise. To do that, first we short the input terminal to ground and then we connect a current source $I_\mathrm{out}$ at the output terminal, see @fig-voltage-buffer-ota-noise-zout.

{{< include /content/ota_basic/_fig_voltage_buffer_ota_noise_zout.qmd >}}

Since we can neglect the gate leakage current into the inverting input terminal of the OTA, KCL at the output node is simply:

$$
I_\mathrm{out} + \gm[12]\left(-V_\mathrm{out}\right) = 0
$$

Thus, the output impedance is easily calculated.

$$
Z_\mathrm{out} = \frac{V_\mathrm{out}}{I_\mathrm{out}} = \frac{V_\mathrm{out}}{\gm[12]V_\mathrm{out}} = \frac{1}{\gm[12]}
$$

:::

{{< include /content/ota_basic/_fig_voltage_buffer_ota_noise.qmd >}}

We see that the feedback around the transconductor $\gm[1,2]$ creates an impedance of $1/\gm[1,2]$. We can now calculate the effective load conductance of
$$
Y'_\mathrm{load} = \gds[2] + \gds[4] + s C_\mathrm{load} + \gm[1,2] \approx \gm[1,2] + s C_\mathrm{load}.
$$ {#eq-basic-ota-output-noise-yload}

The output noise voltage is then (using @eq-mosfet-noise)
$$
\overline{V_\mathrm{n,out}^2}(f) = \frac{\overline{I_\mathrm{n}^2}}{|Y'_\mathrm{load}|^2} = \frac{\overline{I_\mathrm{n}^2}}{\gm[1,2]^2 + (2 \pi f C_\mathrm{load})2^2} = \frac{8 k T (\gamma_{1,2} \gm[1,2] + \gamma_{3,4} \gm[3,4])}{\gm[1,2]^2 + (2 \pi f C_\mathrm{load})^2}.
$$

We can use the identity @eq-integral-identity to calculate the rms output noise to
$$
V_\mathrm{n,out,rms}^2 = \int_0^\infty \overline{V_\mathrm{n,out}^2}(f) df = \frac{k T}{C_\mathrm{load}} \left( 2 \gamma_{1,2} + 2 \gamma_{3,4} \frac{\gm[3,4]}{\gm[1,2]} \right).
$$ {#eq-basic-ota-output-noise}

Inspecting @eq-basic-ota-output-noise we can see that the integrated output noise is the $k T / C$ noise of the output load capacitor, enhanced by the $\gamma_{12}$ of the input differential pair, plus a (smaller) contribution of the current mirror load $M_{3,4}$. Intuitively, this result makes sense.

::: {.callout-tip title="Exercise: Derivation of 5T-OTA Performance"}
Please take your time and carefully go through the explanations and derivations for the 5-transistor-OTA in @sec-basic-ota-large-signal and @sec-basic-ota-small-signal. Try to do the calculations yourself; if you get stuck, review the previous chapters.
:::

## 5T-OTA Sizing {#sec-basic-ota-sizing}

Outfitted with the governing equations derived in @sec-basic-ota-small-signal we can now size the MOSFETs in the OTA, we remember that we have to size $M_{1,2}$ and $M_{3,4}$ equally.

First, we need to select a proper $\gmid$ for the MOSFET. Remembering @sec-gmid-method we see that for the input differential pair we should go for a large $\gm$, thus we select a $\gmid = 10$. As $\gds$ of $M_2$ could limit the dc gain (@eq-simple-ota-gain-dc) we go with a rather long $L = 5\,\mu\text{m}$. For current sources a small $\gmid$ is a good idea, so we start with $\gmid=5$ (because we can not go too low because of $V_\mathrm{ds,sat}$) and also an $L = 5\,\mu\text{m}$. The $\gmid$ is also useful to estimate the required drain-source voltage to keep a MOSFET in saturation (i.e., keep the $\gds$ small) with this approximate relationship:

$$
\Vds[,sat] = \frac{2}{\gmid}
$$ {#eq-gmid-saturation}

::: {.callout-tip title="Exercise: 5T-OTA Sizing"}
Please size the 5T-OTA according to the previous $\gmid$ and $L$ suggestions. Please calculate the $W$ of $M_{1-6}$ and the total supply current. Please check wether gain error, total output noise, and turn-on settling is met with the calculated devices sizes and bias currents.
:::

The sizing procedure and its calculation are best performed in a Jupyter notebook, as we can easily look up the exact data from the pre-computed tables:

::: {.callout-tip title="Solution: 5T-OTA Sizing" collapse="true"}
{{< embed ./gmid/sizing_basic_ota.ipynb echo=true >}}
:::

## 5T-OTA Simulation {#sec-basic-ota-simulation}

With the initial sizing of the MOSFETs of the 5T-OTA done, we can design the 5T-OTA circuit and setup a simulation testbench to check the performance parameters. Since this is the first time we draw a more complex schematic, and use a hierarchical design, we should note that drawing a schematic is an art, and there exists a set of rules and recommendations how to name pins, how to use annotations, and so on. Please read @sec-designers-etiquette before you start into your design work.

::: {.callout-tip title="Exercise: 5T-OTA Design and Testbench"}
Please design the circuit of the 5T-OTA. Put the OTA circuit in a separate schematic, create a symbol for it, and use this symbol in a testbench you create in Xschem for this 5T-OTA used as a voltage buffer as shown in @fig-voltage-buffer-ota. Use typical conditions for the simulation, and check how well the specification in @tbl-voltage-buffer-spec is met, and how well the derivations in @sec-basic-ota-large-signal and @sec-basic-ota-small-signal fit to the simulation results.

If you get stuck, you can find the testbench and 5T-OTA schematic [here](./xschem/ota-5t_tb-ac.svg) (for the small-signal analysis) and [here](./xschem/ota-5t_tb-tran.svg) (for the large-signal settling simulation). For interested students, the loop gain analysis with Middlebrook's and Tian's method of the 5T-OTA can be found [here](./xschem/ota-5t_tb-loopgain.svg).
:::

## MOSFET Mismatch {#sec-mosfet-mismatch}

So far, we have assumed that implemented MOSFETs show no difference from device to device, which means that two transistors behave completely identical, and the resulting differential circuits are fully symmetric. However, due to manufacturing tolerances, this is not the case in reality. MOSFETs will show **mismatch** due to tiny random fluctuations in manufacturing, and we have to account for this.

For a typical MOSFET, we usually consider two main mismatch effects [@Pelgrom_1989]:

- A variation of the threshold voltage (mainly due to variations in doping levels).
- A variation of the critical dimensions of the MOSFET ($W$ and $L$ as well as vertical dimensions).

Both effects influence the drain current of the MOSFET, and they are indirectly proportional to the size of the MOSFET. So, if we want to reduce the mismatch, we have to increase the size of the MOSFET by increasing its gate area $W \cdot L$.

If we formulate the drain current mismatch $\Delta \ID / \ID$ of two nominally identical MOSFET we get

$$
\frac{\Delta \ID}{\ID} = \frac{A_\mathrm{mosfet}}{\sqrt{W L}}
$$ {#eq-mosfet-mismatch}

with $A_\mathrm{mosfet}$ being a mismatch parameter for a given CMOS technology.

::: {.callout-note title="MOSFET Mismatch"}
Usually, the mismatch in MOSFETs is characterized via two mismatch parameters [@Pelgrom_1989]:

- The threshold voltage mismatch

$$
\Delta \Vth = \frac{A_\mathrm{vth}}{\sqrt{W L}}
$$ {#eq-mosfet-mismatch-vth}

- and the size mismatch

$$
\frac{\Delta (W/L)}{(W/L)} = \frac{A_\mathrm{k}}{\sqrt{W L}}.
$$ {#eq-mosfet-mismatch-kp}

The resulting input offset voltage $V_\mathrm{offs}$ of a differential pair is then given by [@Razavi_Analog_CMOS]
$$
V_\mathrm{offs} = \sqrt{\left( \frac{\VGS - \Vth}{2} \frac{\Delta (W/L)}{{(W/L)}} \right)^2 + \Delta \Vth^2}.
$$ {#eq-diffpair-offset}

The mismatch in the drain current of two current-mirror transistors is given by [@Razavi_Analog_CMOS]

$$
\frac{\Delta \ID}{\ID} = \frac{\Delta (W/L)}{(W/L)} - 2 \frac{\Delta \Vth}{\VGS - \Vth}.
$$ {#eq-currentmirror-offset}

To minimize the input offset voltage in a differential pair we should strive to minimize $\VGS$ (see @eq-diffpair-offset) and to minimize the mismatch in current mirrors we should target a large $\VGS$ (see @eq-currentmirror-offset). In both cases the MOSFET area $W \cdot L$ needs to be large enough (see @eq-mosfet-mismatch-vth and @eq-mosfet-mismatch-kp).
:::

How can we now cope with mismatch in design and simulation? We can account the transitor mismatch according to @eq-mosfet-mismatch-vth and @eq-mosfet-mismatch-kp in circuit analysis and quantify its effect. We can then take this into account when performing the circuit sizing procedure.

We can also simulate the effects of MOSFET mismatch on circuit performance by doing a [**Monte Carlo**](https://en.wikipedia.org/wiki/Monte_Carlo_method) simulation. Here, a random realization of the variations of all circuit components (where mismatch is modelled) is taken and the circuit is simulated. Then, another random realization is simulated, and so on. In summary, we run the same simulation for different realizations $N$ times and evaluate the resulting variations of the circuit parameters. If $N$ is large enough then the distributions should approach a [Gaussian distribution](https://en.wikipedia.org/wiki/Normal_distribution), and we can then estimate the variances of the circuit parameters. Using statistical analysis we can then assess the [**yield**](https://en.wikipedia.org/wiki/Semiconductor_device_fabrication#Device_yield) of a circuit, i.e., how many circuit realizations will meet the specification.

::: {.callout-note title="Number of Monte Carlo Simulation Runs"}
The number of Monte Carlo simulation runs $N$ has to be large enough to approach Gaussian distributions to allow estimation of the variances. However, this comes at the cost of a large simulation time, so a balance has to be found. Often, $N = 250$ is a good compromise between simulation time and well-behaved parameter distributions.
:::

As you can see in the previous discussion, running Monte Carlo simulations is a tedious process due to the large number of involved simulations and the required data processing of the heaps of simulation data. Luckily, CACE supports this type of simulation, and we will use it in @sec-basic-ota-simulation-pvt.

## Resistor Mismatch {#sec-resistor-mismatch}

Similar to the MOSFET mismatch discussed in @sec-mosfet-mismatch, resistors will also show mismatch. Equivalently to @eq-mosfet-mismatch the resistor mismatch $\Delta R / R$ can be characterized by

$$
\frac{\Delta R}{R} = \frac{A_\mathrm{res}}{\sqrt{W L}}
$$ {#eq-resistor-mismatch}

with $A_\mathrm{res}$ being a mismatch parameter for a given CMOS technology.

With @eq-resistor-mismatch we now have two criteria for how to select the width $W$ of a specific resistor (the length $L$ is then derived from the required resistance value with $R = R_\square \cdot L / W$):

1. The current handling capability (the larger the $W$, the more dc current a resistor can carry), and
2. the resistor mismatch (the larger the $W$, the larger the $W L$ for a given $L/W$).

If a resistor's dimensions are not limited by the two criteria above then we usually choose the minimum width that is allowed for a given resistor in a specific technology (for SG13G2 it is $L_\mathrm{min} = 0.5\,\mu\text{m}$) to save area and to minimize the parasitic capacitance of the resistor to substrate. 

## 5T-OTA Simulation versus PVT and MC {#sec-basic-ota-simulation-pvt}

As you have seen in @sec-basic-ota-simulation running simulations by hand is tedious. When we want to check the overall performance, we have to run many simulations over various conditions:

1. The supply voltage of the circuit has tolerances, and thus we need to check the performance against this variation.
2. The temperature at which the circuit is operated is likely changing. Also the performance against this has to be verified.
3. When manufacturing the wafers random variations in various process parameters lead to changed parameters of the integrated circuit components. In order to check for this effect, wafer foundries provide model files which shall cover these manufacturing excursions. Simplified, this leads to a slower or faster MOSFET, and usually NMOS and PMOS are not correlated, so we have the process corners **SS**, **SF**, **TT**, **FS**, and **FF**. So far, we have only used the **TT** models in our simulations.

The variations listed in the previous list are abbreviated as **PVT** (process, voltage, temperature) variations. In order to finalize a circuit all combinations of these (plus the variations in operating conditions like input voltage) have to be simulated. As you can imagine, this leads to a huge number of simulations, and simulation results which have to be evaluated for pass/fail.

There are two options how to tackle this efficiently:

1. As an experienced designer you have a very solid understanding of the circuit, plus based on the analytic equations you can identify which combination of operating conditions will lead to a worst case performance. Thus, you can drastically reduce the number of corners to simulate, and you run them by hand.
2. You are using a framework which highly automates this task of running a plethora of different simulations and evaluating the outcome. These frameworks are called simulation runners.

Luckily, there are open-source versions of simulation runners available, and we will use [CACE](https://github.com/efabless/cace) in this lecture. CACE is written in Python and allows to setup a datasheet in [YAML](https://yaml.org) which defines the simulation problem and the performance parameters to evaluate against which limits. The resulting simulations are then run in parallel and the simulation data is evaluated and summarized in various forms.

There is a CACE setup available for our 5T-OTA. The [datasheet](./cace/voltage-buffer-ota.yaml) describes the operating conditions and the simulations tasks. For each simulation a testbench template is needed, [this one](./cace/templates/ota-5t-ac.sch) is used for ac simulations, [this one](./cace/templates/ota-5t-noise.sch) is used for noise simulation, and [this one](./cace/templates/ota-5t-tran.sch) is used for transient simulation.

::: {.callout-warning title="Running CACE Simulation"}

The CACE simulation run can be started with

```bash
cace cace/voltage-buffer-ota.yaml
```

The simulation results are then placed into the `cace/_docs` folder. If in addition to the default Markdown report an HTML output is needed for easier review then using Pandoc it can be easily converted and viewed with with 

```bash
cace/cace_view.sh cace/_docs/ota-5t_schematic.md
```

:::

After a successful run, a documentation is automatically generated. The result of a full run of this [OTA design](./xschem/ota-5t.svg) is presented here:

::: {#nte-basic-ota-cace-result .callout-note title="CACE Summary for 5T-OTA" collapse="true"}

{{< include /cace/_docs/ota-5t_schematic.md >}}
:::

### PVT Simulation Analysis

Looking at the CACE report in @nte-basic-ota-cace-result we see that (luckily) the specification is met for all parameters. This is great news! We now have a design that we carefully simulated across PVT and other corners, and which is ready for layout. Once we have the layout ready, we can extract the wiring parasitic ($R$ and $C$) as well as other layout-dependent effects like [well proximity](https://global.oup.com/us/companion.websites/9780195170153/pdf/proximityeffectmodels.pdf). Using this augmented netlist we can then again use CACE to check performance across conditions and parameter variations, and if we still pass all specification points then our design is finished.

### Monte Carlo Simulation Analysis

Looking at the CACE report in @nte-basic-ota-cace-result we see that the output voltage specification is not met due to MOSFET mismatch! We have not considered transistor mismatch in the circuit sizing procedure, and as a result the selected MOSFET dimensions proof to be too small. We should now go back and change the transistor sizing (increasing $L$ significantly while keeping the $\gmid$ values). Likely we will find that some performance parameters are now deteriorating due to the increased MOSFET dimensions, and we need to iterate until all performance metrics are met in the presence of transistor mismatch.

It is not unusual that the power consumption now increases, as we have to increase the size of the MOSFETs for matching, and these larger MOSFETs increase the parasitic capacitances which in turn lead to larger power consumption to keep the required bandwidth by increasing the $\gm$.

::: {.callout-tip title="Exercise: Re-Sizing of 5T-OTA for Mismatch"}
Go back to @sec-basic-ota-sizing and repeat the sizing procedure of the 5T-OTA by increasing the $L$ of the MOSFETs significantly. Focus first on the differential pair as it will likely have the biggest impact (see @eq-diffpair-offset). Then, tune the size of the output current mirror if necessary (see @eq-currentmirror-offset).

Once you are happy with the sizing result repeat the PVT simulations in CACE to confirm the performance of the voltage buffer including mismatch.
:::

## OTA Variants {#sec-ota-variants-single-ended}

Following, we are going to discuss two popular variants of the simple 5T-OTA. The first version provides an almost rail-to-rail single-ended output, and can thus be used for a variety of applications requiring this range. The arrangement is shown in @fig-ota-se-rail-to-rail. It is a single-stage amplifier, as the only high-impedance point is at the output where significant voltage-gain is produced. The current mirrors can be used to scale up the current generated in the input differential pair to some extent in the output stage (or can be used to lower the current compared to the bias current in the diffpair); i.e., the bias currents of the input stage and the output stage can be set independently.

Being a single-stage amplifier stability is usually not an issue, as only the output node is high-ohmic; all other nodes feature a MOSFET diode so the node impedance is $\approx \gm^{-1}$ and thus the according poles are located at high frequencies.

{{< include /content/ota_basic/_fig_ota_se_r2r.qmd >}}

Another popular version is shown in @fig-ota-se-twostage. Here, we have a two-stage amplifier able to provide higher voltage gain. The first stage (the diffpair loaded by a current mirror) is followed by a single-stage common-source amplifier with current-source load. Being a two-stage amplifier with two high-ohmic nodes, stability is a concern, so usually we need some form of compensation. @fig-ota-se-twostage shows a very simplistic Miller-compensation using $C_\mathrm{M}$. Often, we would want to implement a more advanced scheme. Some examples can be found in [@Baker_compensating_OPAMP]. An interesting technique is the indirect compensation with cascoded input differential pairs (see @fig-improved-ota) for higher power supply rejection. An advantage of this two-stage amplifier (compared with the simple 5T-OTA) is the dc-balanced load on top of the differential pair, as each side sees a voltage drop from $\VDD$ of one $\VGS$ ($\VGS[3]$ on the left side, $\VGS[5]$ on the right side).

{{< include /content/ota_basic/_fig_ota_se_twostage.qmd >}}

Note that the circuit of @fig-ota-se-twostage can be easily modified into a low-dropout voltage regulator (LDO). This simple yet often effective circuit is shown in @fig-simple-ldo. The pass transistor $M_\mathrm{pass}$ has to be sized according to the load current and the dropout voltage.

{{< include /content/ota_basic/_fig_simple_ldo.qmd >}}

The reference voltage $V_\mathrm{ref}$ is scaled by $R_1$ and $R_2$, so that the output voltage $V_\mathrm{out}$ is given by

$$
V_\mathrm{out} \approx V_\mathrm{ref} \left( 1 + \frac{R_1}{R_2} \right)
$$

if the gain of the OTA is sufficiently high. The quiescent current through $R_{1,2}$ establishes a minimum load current for the LDO, which is often good for stability. More information on LDOs can be found in [@Razavi_2019_ldo].
